--
-- Countries
-- Updated: 2013-09-19 at 11:39 GMT
-- Copyright (c) 2012-2013 Peter Kahl. All rights reserved.
-- Use of this source code is governed by a GNU General Public License
-- that can be found in the LICENSE file.
--
-- https://github.com/peterkahl/countries
--

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

-- --------------------------------------------------------

--
-- Table structure for table `countries`
--

CREATE TABLE IF NOT EXISTS `countries` (
  `code` varchar(4) NOT NULL DEFAULT '',
  `iso_country` varchar(255) NOT NULL DEFAULT '',
  `country_ar_SA` varchar(255) NOT NULL,
  `country_cs_CZ` varchar(255) NOT NULL,
  `country_de_DE` varchar(255) NOT NULL,
  `country_es_ES` varchar(255) NOT NULL,
  `country_fr_FR` varchar(255) NOT NULL,
  `country_nl_NL` varchar(255) NOT NULL,
  `country_ja_JP` varchar(255) NOT NULL,
  `country_pt_PT` varchar(255) NOT NULL,
  `country_it_IT` varchar(255) NOT NULL,
  `country_ru_RU` varchar(255) NOT NULL,
  `country_en_GB` varchar(255) NOT NULL,
  `country_zh_TW` varchar(255) NOT NULL,
  `country_zh_CN` varchar(255) NOT NULL,
  `lat` float NOT NULL DEFAULT '0',
  `lon` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`code`),
  KEY `code` (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `countries`
--

INSERT INTO `countries` (`code`, `iso_country`, `country_ar_SA`, `country_cs_CZ`, `country_de_DE`, `country_es_ES`, `country_fr_FR`, `country_nl_NL`, `country_ja_JP`, `country_pt_PT`, `country_it_IT`, `country_ru_RU`, `country_en_GB`, `country_zh_TW`, `country_zh_CN`, `lat`, `lon`) VALUES
('ad', 'Andorra', 'أندورا', 'Andorra', 'Andorra', 'Andorra', 'Andorre', 'Andorra', 'アンドラ', 'Andorra', 'Andorra', 'Андорра', 'Andorra', '安道爾', '安道尔', 42.3, 1.3),
('ae', 'United Arab Emirates', 'الامارات العربية المتحدة', 'Spojené arabské emiráty', 'Vereinigte Arabische Emirate', 'Emiratos Árabes Unidos', 'Émirats arabes unis', 'Verenigde Arabische Emiraten', 'アラブ首長国連邦', 'Emiratos Árabes Unidos', 'Emirati Arabi Uniti', 'Объединенные Арабские Эмираты', 'United Arab Emirates', '阿拉伯聯合大公國', '阿拉伯联合大公国', 24, 54),
('af', 'Afghanistan', 'أفغانستان', 'Afghánistán', 'Afghanistan', 'Afganistán', 'Afghanistan', 'Afghanistan', 'アフガニスタン', 'Afeganistão', 'Afghanistan', 'Афганистан', 'Afghanistan', '阿富汗', '阿富汗', 33, 65),
('ag', 'Antigua and Barbuda', 'أنتيجوا وبربودا', 'Antigua a Barbuda', 'Antigua und Barbuda', 'Antigua y Barbuda', 'Antigua-et-Barbuda', 'Antigua en Barbuda', 'アンティグア・バーブーダ', 'Antígua e Barbuda', 'Antigua e Barbuda', 'Антигуа и Барбуда', 'Antigua and Barbuda', '安提瓜和巴布達', '安提瓜和巴布达', 17.03, -61.48),
('ai', 'Anguilla', 'أنجويلا', 'Anguila', 'Anguilla', 'Anguila', 'Anguilla', 'Anguilla', 'アンギラ', 'Anguilha', 'Anguilla', 'Ангуилла', 'Anguilla', '安圭拉', '安圭拉', 18.15, -63.1),
('al', 'Albania', 'ألبانيا', 'Albánie', 'Albanien', 'Albania', 'Albanie', 'Albanië', 'アルバニア', 'Albânia', 'Albania', 'Албания', 'Albania', '阿爾巴尼亞', '阿尔巴尼亚', 41, 20),
('am', 'Armenia', 'أرمينيا', 'Arménie', 'Armenien', 'Armenia', 'Arménie', 'Armenië', 'アルメニア', 'Arménia', 'Armenia', 'Армения', 'Armenia', '亞美尼亞', '亚美尼亚', 40, 45),
('an', 'Netherlands Antilles', 'جزر الأنتيل الهولندية', 'Nizozemské Antily', 'Niederländische Antillen', 'Antillas Neerlandesas', 'Antilles néerlandaises', 'Nederlandse Antillen', 'オランダ領アンティル諸島', 'Antilhas Holandesas', 'Antille Olandesi', 'Нидерландские Антильские острова', 'Netherlands Antilles', '荷屬安的列斯群島', '荷属安的列斯群岛', 12.15, -68.45),
('ao', 'Angola', 'أنجولا', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'アンゴラ', 'Angola', 'Angola', 'Ангола', 'Angola', '安哥拉', '安哥拉', -12.3, 18.3),
('aq', 'Antarctica', 'القطب الجنوبي', 'Antarktida', 'Antarktis', 'Antártida', 'Antarctique', 'Antarctica', '南極大陸', 'Antárctica', 'Antartide', 'Антарктика', 'Antarctica', '南極洲', '南极洲', -90, 0),
('ar', 'Argentina', 'الأرجنتين', 'Argentina', 'Argentinien', 'Argentina', 'Argentine', 'Argentinië', 'アルゼンチン', 'Argentina', 'Argentina', 'Аргентина', 'Argentina', '阿根廷', '阿根廷', -34, -64),
('as', 'American Samoa', 'ساموا الأمريكية', 'Americká Samoa', 'Amerikanisch-Samoa', 'Samoa Americana', 'Samoa américaines', 'Amerikaans Samoa', '米領サモア', 'Samoa Americana', 'Samoa Americane', 'Американское Самоа', 'American Samoa', '美屬薩摩亞', '美属萨摩亚', -14.2, -170),
('at', 'Austria', 'النمسا', 'Rakousko', 'Österreich', 'Austria', 'Autriche', 'Oostenrijk', 'オーストリア', 'Áustria', 'Austria', 'Австрия', 'Austria', '奧地利', '奥地利', 47.2, 13.2),
('au', 'Australia', 'أستراليا', 'Austrálie', 'Australien', 'Australia', 'Australie', 'Australië', 'オーストラリア', 'Austrália', 'Australia', 'Австралия', 'Australia', '澳大利亞', '澳大利亚', -27, 133),
('aw', 'Aruba', 'آروبا', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'アルバ島', 'Aruba', 'Aruba', 'Аруба', 'Aruba', '阿魯巴', '阿鲁巴', 12.3, -69.58),
('az', 'Azerbaijan', 'أذربيجان', 'Ázerbájdžán', 'Aserbaidschan', 'Azerbaiyán', 'Azerbaïdjan', 'Azerbeidzjan', 'アゼルバイジャン', 'Azerbeijão', 'Azerbaigian', 'Азербайджан', 'Azerbaijan', '阿塞拜疆', '阿塞拜疆', 40.3, 47.3),
('ba', 'Bosnia and Herzegovina', 'البوسنة والهرسك', 'Bosna a Hercegovina', 'Bosnien und Herzegowina', 'Bosnia-Herzegovina', 'Bosnie-Herzégovine', 'Bosnië en Herzegovina', 'ボスニア・ヘルツェゴビナ', 'Bósnia-Herzegovina', 'Bosnia Erzegovina', 'Босния и Герцеговина', 'Bosnia and Herzegovina', '波斯尼亞和黑塞哥維那', '波斯尼亚和黑塞哥维那', 44, 18),
('bb', 'Barbados', 'بربادوس', 'Barbados', 'Barbados', 'Barbados', 'Barbade', 'Barbados', 'バルバドス', 'Barbados', 'Barbados', 'Барбадос', 'Barbados', '巴巴多斯', '巴巴多斯', 13.1, -59.32),
('bd', 'Bangladesh', 'بنجلاديش', 'Bangladéš', 'Bangladesch', 'Bangladesh', 'Bangladesh', 'Bangladesh', 'バングラデシュ', 'Bangladeche', 'Bangladesh', 'Бангладеш', 'Bangladesh', '孟加拉國', '孟加拉国', 24, 90),
('be', 'Belgium', 'بلجيكا', 'Belgie', 'Belgien', 'Bélgica', 'Belgique', 'België', 'ベルギー', 'Bélgica', 'Belgio', 'Бельгия', 'Belgium', '比利時', '比利时', 50.5, 4),
('bf', 'Burkina Faso', 'بوركينا فاسو', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'ブルキナファソ', 'Burkina-Faso', 'Burkina Faso', 'Буркина Фасо', 'Burkina Faso', '布基納法索', '布基纳法索', 13, -2),
('bg', 'Bulgaria', 'بلغاريا', 'Bulharsko', 'Bulgarien', 'Bulgaria', 'Bulgarie', 'Bulgarije', 'ブルガリア', 'Bulgária', 'Bulgaria', 'Болгария', 'Bulgaria', '保加利亞', '保加利亚', 43, 25),
('bh', 'Bahrain', 'البحرين', 'Bahrajn', 'Bahrain', 'Bahréin', 'Bahreïn', 'Bahrein', 'バーレーン', 'Bahrein', 'Bahrein', 'Бахрейн', 'Bahrain', '巴林', '巴林', 26, 50.33),
('bi', 'Burundi', 'بوروندي', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'ブルンジ', 'Burundi', 'Burundi', 'Бурунди', 'Burundi', '布隆迪', '布隆迪', -3.3, 30),
('bj', 'Benin', 'بنين', 'Benin', 'Benin', 'Benín', 'Bénin', 'Benin', 'ベニン', 'Benim', 'Benin', 'Бенин', 'Benin', '貝寧', '贝宁', 9.3, 2.15),
('bm', 'Bermuda', 'برمودا', 'Bermudy', 'Bermuda', 'Bermudas', 'Bermudes', 'Bermuda', 'バミューダ', 'Bermudas', 'Bermuda', 'Бермудские Острова', 'Bermuda', '百慕大', '百慕大', 32.2, -64.45),
('bn', 'Brunei Darussalam', 'بروناي', 'Brunej Darussalam', 'Brunei Darussalam', 'Brunéi', 'Brunéi Darussalam', 'Brunei', 'ブルネイ', 'Brunei', 'Brunei', 'Бруней Даруссалам', 'Brunei Darussalam', '文萊', '文莱', 4.3, 114.4),
('bo', 'Bolivia', 'بوليفيا', 'Bolívie', 'Bolivien', 'Bolivia', 'Bolivie', 'Bolivia', 'ボリビア', 'Bolívia', 'Bolivia', 'Боливия', 'Bolivia', '玻利維亞', '玻利维亚', -17, -65),
('br', 'Brazil', 'البرازيل', 'Brazílie', 'Brasilien', 'Brasil', 'Brésil', 'Brazilië', 'ブラジル', 'Brasil', 'Brasile', 'Бразилия', 'Brazil', '巴西', '巴西', -10, -55),
('bs', 'Bahamas', 'الباهاما', 'Bahamy', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahama’s', 'バハマ', 'Baamas', 'Bahamas', 'Багамские острова', 'Bahamas', '巴哈馬', '巴哈马', 24.15, -76),
('bt', 'Bhutan', 'بوتان', 'Bhútán', 'Bhutan', 'Bután', 'Bhoutan', 'Bhutan', 'ブータン', 'Butão', 'Bhutan', 'Бутан', 'Bhutan', '不丹', '不丹', 27.3, 90.3),
('bv', 'Bouvet Island', 'جزيرة بوفيه', 'Ostrov Bouvet', 'Bouvetinsel', 'Isla Bouvet', 'Île Bouvet', 'Bouveteiland', 'ブーベ島', 'Ilha Bouvet', 'Isola Bouvet', 'Остров Буве', 'Bouvet Island', '布維島', '布维岛', -54.26, 3.24),
('bw', 'Botswana', 'بتسوانا', 'Botswana', 'Botsuana', 'Botsuana', 'Botswana', 'Botswana', 'ボツワナ', 'Botswana', 'Botswana', 'Ботсвана', 'Botswana', '博茨瓦納', '博茨瓦纳', -22, 24),
('by', 'Belarus', 'روسيا البيضاء', 'Bělorusko', 'Belarus', 'Bielorrusia', 'Bélarus', 'Wit-Rusland', 'ベラルーシ', 'Bielorrússia', 'Bielorussia', 'Беларусь', 'Belarus', '白俄羅斯', '白俄罗斯', 53, 28),
('bz', 'Belize', 'بليز', 'Belize', 'Belize', 'Belice', 'Belize', 'Belize', 'ベリーズ', 'Belize', 'Belize', 'Белиз', 'Belize', '伯利茲', '伯利兹', 17.15, -88.45),
('ca', 'Canada', 'كندا', 'Kanada', 'Kanada', 'Canadá', 'Canada', 'Canada', 'カナダ', 'Canadá', 'Canada', 'Канада', 'Canada', '加拿大', '加拿大', 60, -95),
('cc', 'Cocos (Keeling) Islands', 'جزر كوكوس', 'Kokosové ostrovy', 'Kokosinseln', 'Islas Cocos', 'Îles Cocos - Keeling', 'Cocoseilanden', 'ココス (キーリング) 諸島', 'Ilhas Cocos', 'Isole Cocos', 'Кокосовые острова', 'Cocos (Keeling) Islands', '科科斯群島', '科科斯群岛', -12.3, 96.5),
('cf', 'Central African Republic', 'جمهورية افريقيا الوسطى', 'Středoafrická republika', 'Zentralafrikanische Republik', 'República Centroafricana', 'République centrafricaine', 'Centraal-Afrikaanse Republiek', '中央アフリカ共和国', 'República Centro-Africana', 'Repubblica Centrafricana', 'Центрально-Африканская Республика', 'Central African Republic', '中非共和國', '中非共和国', 7, 21),
('cg', 'Congo', 'الكونغو - برازافيل', 'Kongo', 'Kongo', 'Congo', 'Congo', 'Congo', 'コンゴ共和国 (ブラザビル)', 'Congo-Brazzaville', 'Congo', 'Конго', 'Congo', '剛果', '刚果', 0, 25),
('ch', 'Switzerland', 'سويسرا', 'Švýcarsko', 'Schweiz', 'Suiza', 'Suisse', 'Zwitserland', 'スイス', 'Suíça', 'Svizzera', 'Швейцария', 'Switzerland', '瑞士', '瑞士', 47, 8),
('ck', 'Cook Islands', 'جزر كوك', 'Cookovy ostrovy', 'Cookinseln', 'Islas Cook', 'Îles Cook', 'Cookeilanden', 'クック諸島', 'Ilhas Cook', 'Isole Cook', 'Острова Кука', 'Cook Islands', '庫克群島', '库克群岛', -21.14, -159.46),
('cl', 'Chile', 'شيلي', 'Chile', 'Chile', 'Chile', 'Chili', 'Chili', 'チリ', 'Chile', 'Cile', 'Чили', 'Chile', '智利', '智利', -30, -71),
('cm', 'Cameroon', 'الكاميرون', 'Kamerun', 'Kamerun', 'Camerún', 'Cameroun', 'Kameroen', 'カメルーン', 'República dos Camarões', 'Camerun', 'Камерун', 'Cameroon', '喀麥隆', '喀麦隆', 6, 12),
('cn', 'China', 'الصين', 'Čína', 'China', 'China', 'Chine', 'China', '中国', 'China', 'Cina', 'Китай', 'China', '中國', '中国', 35, 105),
('co', 'Colombia', 'كولومبيا', 'Kolumbie', 'Kolumbien', 'Colombia', 'Colombie', 'Colombia', 'コロンビア', 'Colômbia', 'Colombia', 'Колумбия', 'Colombia', '哥倫比亞', '哥伦比亚', 4, -72),
('cr', 'Costa Rica', 'كوستاريكا', 'Kostarika', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'コスタリカ', 'Costa Rica', 'Costa Rica', 'Коста-Рика', 'Costa Rica', '哥斯達黎加', '哥斯达黎加', 10, -84),
('cs', 'Serbia and Montenegro', 'صربيا والجبل الأسود', 'Srbsko a Černá Hora', 'Serbien und Montenegro', 'Serbia y Montenegro', 'Serbie-et-Monténégro', 'Servië en Montenegro', 'セルビア・モンテネグロ', 'Sérvia e Montenegro', 'Serbia e Montenegro', 'Сербия и Черногория', 'Serbia and Montenegro', '塞爾維亞和黑山', '塞尔维亚和黑山', 43.57, 21.41),
('cu', 'Cuba', 'كوبا', 'Kuba', 'Kuba', 'Cuba', 'Cuba', 'Cuba', 'キューバ', 'Cuba', 'Cuba', 'Куба', 'Cuba', '古巴', '古巴', 21.3, -80),
('cv', 'Cape Verde', 'الرأس الأخضر', 'Kapverdy', 'Kap Verde', 'Cabo Verde', 'Cap-Vert', 'Kaapverdië', 'カーボベルデ', 'Cabo Verde', 'Capo Verde', 'Острова Зеленого Мыса', 'Cape Verde', '佛得角', '佛得角', 16, -24),
('cx', 'Christmas Island', 'جزيرة الكريسماس', 'Vánoční ostrovy', 'Weihnachtsinsel', 'Isla Christmas', 'Île Christmas', 'Christmaseiland', 'クリスマス島', 'Ilha do Natal', 'Isola di Christmas', 'Остров Рождества', 'Christmas Island', '聖誕島', '圣诞岛', -10.3, 105.4),
('cy', 'Cyprus', 'قبرص', 'Kypr', 'Zypern', 'Chipre', 'Chypre', 'Cyprus', 'キプロス', 'Chipre', 'Cipro', 'Кипр', 'Cyprus', '塞浦路斯', '塞浦路斯', 35, 33),
('cz', 'Czech Republic', 'جمهورية التشيك', 'Česká republika', 'Tschechische Republik', 'República Checa', 'République tchèque', 'Tsjechië', 'チェコ共和国', 'República Checa', 'Repubblica Ceca', 'Чешская республика', 'Czech Republic', '捷克', '捷克', 49.45, 15.3),
('de', 'Germany', 'ألمانيا', 'Německo', 'Deutschland', 'Alemania', 'Allemagne', 'Duitsland', 'ドイツ', 'Alemanha', 'Germania', 'Германия', 'Germany', '德國', '德国', 51, 9),
('dj', 'Djibouti', 'جيبوتي', 'Džibuti', 'Dschibuti', 'Yibuti', 'Djibouti', 'Djibouti', 'ジブチ', 'Djibuti', 'Gibuti', 'Джибути', 'Djibouti', '吉布提', '吉布提', 11.3, 43),
('dk', 'Denmark', 'الدانمرك', 'Dánsko', 'Dänemark', 'Dinamarca', 'Danemark', 'Denemarken', 'デンマーク', 'Dinamarca', 'Danimarca', 'Дания', 'Denmark', '丹麥', '丹麦', 56, 10),
('dm', 'Dominica', 'دومينيكا', 'Dominika', 'Dominica', 'Dominica', 'Dominique', 'Dominica', 'ドミニカ国', 'Dominica', 'Dominica', 'Остров Доминика', 'Dominica', '多米尼加', '多米尼加', 15.25, -61.2),
('do', 'Dominican Republic', 'جمهورية الدومينيك', 'Dominikánská republika', 'Dominikanische Republik', 'República Dominicana', 'République dominicaine', 'Dominicaanse Republiek', 'ドミニカ共和国', 'República Dominicana', 'Repubblica Dominicana', 'Доминиканская Республика', 'Dominican Republic', '多米尼加共和國', '多米尼加共和国', 19, -70.4),
('dz', 'Algeria', 'الجزائر', 'Alžírsko', 'Algerien', 'Argelia', 'Algérie', 'Algerije', 'アルジェリア', 'Argélia', 'Algeria', 'Алжир', 'Algeria', '阿爾及利亞', '阿尔及利亚', 28, 3),
('ec', 'Ecuador', 'الاكوادور', 'Ekvádor', 'Ecuador', 'Ecuador', 'Équateur', 'Ecuador', 'エクアドル', 'Equador', 'Ecuador', 'Эквадор', 'Ecuador', '厄瓜多爾', '厄瓜多尔', -2, -77.3),
('ee', 'Estonia', 'استونيا', 'Estonsko', 'Estland', 'Estonia', 'Estonie', 'Estland', 'エストニア', 'Estónia', 'Estonia', 'Эстония', 'Estonia', '愛沙尼亞', '爱沙尼亚', 59, 26),
('eg', 'Egypt', 'مصر', 'Egypt', 'Ägypten', 'Egipto', 'Égypte', 'Egypte', 'エジプト', 'Egipto', 'Egitto', 'Египет', 'Egypt', '埃及', '埃及', 27, 30),
('eh', 'Western Sahara', 'الصحراء الغربية', 'Západní Sahara', 'Westsahara', 'Sáhara Occidental', 'Sahara occidental', 'Westelijke Sahara', '西サハラ', 'Sara Ocidental', 'Sahara Occidentale', 'Западная Сахара', 'Western Sahara', '西撒哈拉', '西撒哈拉', 24.3, -13),
('er', 'Eritrea', 'اريتريا', 'Eritrea', 'Eritrea', 'Eritrea', 'Érythrée', 'Eritrea', 'エリトリア', 'Eritreia', 'Eritrea', 'Эритрея', 'Eritrea', '厄立特里亞', '厄立特里亚', 15, 39),
('es', 'Spain', 'أسبانيا', 'Španělsko', 'Spanien', 'España', 'Espagne', 'Spanje', 'スペイン', 'Espanha', 'Spagna', 'Испания', 'Spain', '西班牙', '西班牙', 40, -4),
('et', 'Ethiopia', 'اثيوبيا', 'Etiopie', 'Äthiopien', 'Etiopía', 'Éthiopie', 'Ethiopië', 'エチオピア', 'Etiópia', 'Etiopia', 'Эфиопия', 'Ethiopia', '埃塞俄比亞', '埃塞俄比亚', 8, 38),
('fi', 'Finland', 'فنلندا', 'Finsko', 'Finnland', 'Finlandia', 'Finlande', 'Finland', 'フィンランド', 'Finlândia', 'Finlandia', 'Финляндия', 'Finland', '芬蘭', '芬兰', 64, 26),
('fj', 'Fiji', 'فيجي', 'Fidži', 'Fidschi', 'Fiyi', 'Fidji', 'Fiji', 'フィジー', 'Fiji', 'Figi', 'Фиджи', 'Fiji', '斐', '斐', -18, 175),
('fk', 'Falkland Islands (Malvinas)', 'جزر فوكلاند', 'Falklandské ostrovy', 'Falklandinseln', 'Islas Malvinas', 'Îles Malouines', 'Falklandeilanden', 'フォークランド諸島', 'Ilhas Falkland ou Malvinas', 'Isole Falkland', 'Фолклендские острова', 'Falkland Islands (Malvinas)', '福克蘭群島', '福克兰群岛', -51.45, -59),
('fm', 'Micronesia', 'ميكرونيزيا', 'Mikronézie', 'Mikronesien', 'Micronesia', 'États fédérés de Micronésie', 'Micronesië', 'ミクロネシア', 'Estados Federados da Micronésia', 'Micronesia', 'Федеративные Штаты Микронезии', 'Micronesia', '密克羅尼西亞', '密克罗尼西亚', 6.55, 158.15),
('fo', 'Faroe Islands', 'جزر فارو', 'Faerské ostrovy', 'Färöer', 'Islas Feroe', 'Îles Féroé', 'Faeröer', 'フェロー諸島', 'Ilhas Faroé', 'Isole Faroe', 'Фарерские острова', 'Faroe Islands', '法羅群島', '法罗群岛', 62, -7),
('fr', 'France', 'فرنسا', 'Francie', 'Frankreich', 'Francia', 'France', 'Frankrijk', 'フランス', 'França', 'Francia', 'Франция', 'France', '法國', '法国', 46, 2),
('ci', 'Cote D’ivoire', 'ساحل العاج', 'Pobřeží slonoviny', 'Côte d’Ivoire', 'Costa de Marfil', 'Côte d’Ivoire', 'Ivoorkust', 'コートジボワール', 'Costa do Marfim', 'Costa d’Avorio', 'Кот д’Ивуар', 'Ivory Coast', '象牙海岸', '象牙海岸', 7.64, -4.93),
('ga', 'Gabon', 'الجابون', 'Gabon', 'Gabun', 'Gabón', 'Gabon', 'Gabon', 'ガボン', 'Gabão', 'Gabon', 'Габон', 'Gabon', '加蓬', '加蓬', -1, 11.45),
('gd', 'Grenada', 'جرينادا', 'Grenada', 'Grenada', 'Granada', 'Grenade', 'Grenada', 'グレナダ', 'Granada', 'Grenada', 'Гренада', 'Grenada', '格林納達', '格林纳达', 12.07, -61.4),
('ge', 'Georgia', 'جورجيا', 'Gruzie', 'Georgien', 'Georgia', 'Géorgie', 'Georgië', 'グルジア', 'Geórgia', 'Georgia', 'Грузия', 'Georgia', '格魯吉亞', '格鲁吉亚', 42, 43.3),
('gf', 'French Guiana', 'غويانا', 'Francouzská Guyana', 'Französisch-Guayana', 'Guayana Francesa', 'Guyane française', 'Frans-Guyana', '仏領ギアナ', 'Guiana Francesa', 'Guiana Francese', 'Французская Гвиана', 'French Guiana', '法屬圭亞那', '法属圭亚那', 4, -53),
('gh', 'Ghana', 'غانا', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'ガーナ', 'Gana', 'Ghana', 'Гана', 'Ghana', '加納', '加纳', 8, -2),
('gi', 'Gibraltar', 'جبل طارق', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'ジブラルタル', 'Gibraltar', 'Gibilterra', 'Гибралтар', 'Gibraltar', '直布羅陀', '直布罗陀', 36.8, -5.21),
('gl', 'Greenland', 'جرينلاند', 'Grónsko', 'Grönland', 'Groenlandia', 'Groenland', 'Groenland', 'グリーンランド', 'Gronelândia', 'Groenlandia', 'Гренландия', 'Greenland', '格陵蘭', '格陵兰', 72, -40),
('gm', 'Gambia', 'غامبيا', 'Gambie', 'Gambia', 'Gambia', 'Gambie', 'Gambia', 'ガンビア', 'Gâmbia', 'Gambia', 'Гамбия', 'Gambia', '岡比亞', '冈比亚', 13.28, -16.34),
('gn', 'Guinea', 'غينيا', 'Guinea', 'Guinea', 'Guinea', 'Guinée', 'Guinee', 'ギニア', 'Guiné', 'Guinea', 'Гвинея', 'Guinea', '幾內亞', '几内亚', 11, -10),
('gp', 'Guadeloupe', 'جوادلوب', 'Guadeloupe', 'Guadeloupe', 'Guadalupe', 'Guadeloupe', 'Guadeloupe', 'グアドループ', 'Guadalupe', 'Guadalupa', 'Гваделупа', 'Guadeloupe', '瓜德羅普島', '瓜德罗普岛', 16.15, -61.35),
('gq', 'Equatorial Guinea', 'غينيا الاستوائية', 'Rovníková Guinea', 'Äquatorialguinea', 'Guinea Ecuatorial', 'Guinée équatoriale', 'Equatoriaal-Guinea', '赤道ギニア', 'Guiné Equatorial', 'Guinea Equatoriale', 'Экваториальная Гвинея', 'Equatorial Guinea', '赤道幾內亞', '赤道几内亚', 2, 10),
('gr', 'Greece', 'اليونان', 'Řecko', 'Griechenland', 'Grecia', 'Grèce', 'Griekenland', 'ギリシャ', 'Grécia', 'Grecia', 'Греция', 'Greece', '希臘', '希腊', 39, 22),
('gs', 'South Georgia and the South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'Jižní Georgie a Jižní Sandwichovy ostrovy', 'Südgeorgien und die Südlichen Sandwichinseln', 'Islas Georgia del Sur y Sandwich del Sur', 'Géorgie du Sud et les îles Sandwich du Sud', 'Zuid-Georgië en Zuidelijke Sandwicheilanden', '南ジョージア島・南サンドイッチ諸島', 'Geórgia do Sul e Ilhas Sandwich do Sul', 'Georgia del Sud e Isole Sandwich del Sud', 'Южная Джорджия и Южные Сандвичевы Острова', 'S. Georgia and S. Sandwich Isls.', '南喬治亞島和南桑威奇群島', '南乔治亚岛和南桑威奇群岛', -54.3, -37),
('gt', 'Guatemala', 'جواتيمالا', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'グアテマラ', 'Guatemala', 'Guatemala', 'Гватемала', 'Guatemala', '危地馬拉', '危地马拉', 15.3, -90.15),
('gu', 'Guam', 'جوام', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'グアム', 'Guam', 'Guam', 'Гуам', 'Guam', '關島', '关岛', 13.28, 144.47),
('gw', 'Guinea-Bissau', 'غينيا بيساو', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'Guinee-Bissau', 'ギニアビサウ', 'Guiné-Bissau', 'Guinea-Bissau', 'Гвинея-Биссау', 'Guinea-Bissau', '幾內亞比紹', '几内亚比绍', 12, -15),
('gy', 'Guyana', 'غيانا', 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'ガイアナ', 'Guiana', 'Guyana', 'Гайана', 'Guyana', '圭亞那', '圭亚那', 5, -59),
('hk', 'Hong Kong', 'هونج كونج الصينية', 'Hongkong', 'Hongkong', 'Hong Kong', 'Hong Kong', 'Hongkong', '香港', 'Hong Kong', 'Hong Kong', 'Гонконг', 'Hong Kong', '香港', '香港', 22.15, 114.1),
('hm', 'Heard Island and Mcdonald Islands', 'جزيرة هيرد وماكدونالد', 'Ostrovy Heard a McDonald', 'Heard- und McDonald-Inseln', 'Islas Heard y McDonald', 'Îles Heard et MacDonald', 'Heard- en McDonaldeilanden', 'ハード島・マクドナルド諸島', 'Ilha Heard e Ilhas McDonald', 'Isole Heard ed Isole McDonald', 'Острова Херд и Макдональд', 'Heard and McDonald Islands', '赫德島和麥當勞群島', '赫德岛和麦当劳群岛', -53.06, 72.31),
('hn', 'Honduras', 'هندوراس', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'ホンジュラス', 'Honduras', 'Honduras', 'Гондурас', 'Honduras', '洪都拉斯', '洪都拉斯', 15, -86.3),
('hr', 'Croatia (Hrvatska)', 'كرواتيا', 'Chorvatsko', 'Kroatien', 'Croacia', 'Croatie', 'Kroatië', 'クロアチア', 'Croácia', 'Croazia', 'Хорватия', 'Croatia (Hrvatska)', '克羅地亞', '克罗地亚', 45.1, 15.3),
('ht', 'Haiti', 'هايتي', 'Haiti', 'Haiti', 'Haití', 'Haïti', 'Haïti', 'ハイチ', 'Haiti', 'Haiti', 'Гаити', 'Haiti', '海地', '海地', 19, -72.25),
('hu', 'Hungary', 'المجر', 'Maďarsko', 'Ungarn', 'Hungría', 'Hongrie', 'Hongarije', 'ハンガリー', 'Hungria', 'Ungheria', 'Венгрия', 'Hungary', '匈牙利', '匈牙利', 47, 20),
('id', 'Indonesia', 'اندونيسيا', 'Indonésie', 'Indonesien', 'Indonesia', 'Indonésie', 'Indonesië', 'インドネシア', 'Indonésia', 'Indonesia', 'Индонезия', 'Indonesia', '印尼', '印尼', -5, 120),
('ie', 'Ireland', 'أيرلندا', 'Irsko', 'Irland', 'Irlanda', 'Irlande', 'Ierland', 'アイルランド', 'Irlanda', 'Irlanda', 'Ирландия', 'Ireland', '愛爾蘭', '爱尔兰', 53, -8),
('il', 'Israel', 'اسرائيل', 'Izrael', 'Israel', 'Israel', 'Israël', 'Israël', 'イスラエル', 'Israel', 'Israele', 'Израиль', 'Israel', '以色列', '以色列', 31.3, 34.45),
('in', 'India', 'الهند', 'Indie', 'Indien', 'India', 'Inde', 'India', 'インド', 'Índia', 'India', 'Индия', 'India', '印度', '印度', 20, 77),
('io', 'British Indian Ocean Territory', 'المحيط الهندي البريطاني', 'Britské území v Indickém oceánu', 'Britisches Territorium im Indischen Ozean', 'Territorio Británico del Océano Índico', 'Territoire britannique de l''océan Indien', 'Britse Gebieden in de Indische Oceaan', '英領インド洋植民地', 'Território Britânico do Oceano Índico', 'Territorio Britannico dell’Oceano Indiano', 'Британская территория в Индийском океане', 'British Indian Ocean Territory', '英屬印度洋領地', '英属印度洋领地', -6, 71.3),
('iq', 'Iraq', 'العراق', 'Irák', 'Irak', 'Iraq', 'Irak', 'Irak', 'イラク', 'Iraque', 'Iraq', 'Ирак', 'Iraq', '伊拉克', '伊拉克', 33, 44),
('ir', 'Iran, Islamic Republic of', 'ايران', 'Írán', 'Iran', 'Irán', 'Iran', 'Iran', 'イラン', 'Irão', 'Iran', 'Иран', 'Iran', '伊朗', '伊朗', 32, 53),
('is', 'Iceland', 'أيسلندا', 'Island', 'Island', 'Islandia', 'Islande', 'IJsland', 'アイスランド', 'Islândia', 'Islanda', 'Исландия', 'Iceland', '冰島', '冰岛', 65, -18),
('it', 'Italy', 'ايطاليا', 'Itálie', 'Italien', 'Italia', 'Italie', 'Italië', 'イタリア', 'Itália', 'Italia', 'Италия', 'Italy', '意大利', '意大利', 42.5, 12.5),
('jm', 'Jamaica', 'جامايكا', 'Jamajka', 'Jamaika', 'Jamaica', 'Jamaïque', 'Jamaica', 'ジャマイカ', 'Jamaica', 'Giamaica', 'Ямайка', 'Jamaica', '牙買加', '牙买加', 18.15, -77.3),
('jo', 'Jordan', 'الأردن', 'Jordánsko', 'Jordanien', 'Jordania', 'Jordanie', 'Jordanië', 'ヨルダン', 'Jordânia', 'Giordania', 'Иордания', 'Jordan', '約旦', '约旦', 31, 36),
('jp', 'Japan', 'اليابان', 'Japonsko', 'Japan', 'Japón', 'Japon', 'Japan', '日本', 'Japão', 'Giappone', 'Япония', 'Japan', '日本', '日本', 36, 138),
('ke', 'Kenya', 'كينيا', 'Keňa', 'Kenia', 'Kenia', 'Kenya', 'Kenia', 'ケニア', 'Quénia', 'Kenya', 'Кения', 'Kenya', '肯尼亞', '肯尼亚', 1, 38),
('kg', 'Kyrgyzstan', 'قرغيزستان', 'Kyrgyzstán', 'Kirgisistan', 'Kirguistán', 'Kirghizistan', 'Kirgizië', 'キルギスタン', 'Quirguizistão', 'Kirghizistan', 'Кыргызстан', 'Kyrgyzstan', '吉爾吉斯斯坦', '吉尔吉斯斯坦', 41, 75),
('kh', 'Cambodia', 'كمبوديا', 'Kambodža', 'Kambodscha', 'Camboya', 'Cambodge', 'Cambodja', 'カンボジア', 'Camboja', 'Cambogia', 'Камбоджа', 'Cambodia', '柬埔寨', '柬埔寨', 13, 105),
('ki', 'Kiribati', 'كيريباتي', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'キリバス', 'Quiribati', 'Kiribati', 'Кирибати', 'Kiribati', '基里巴斯', '基里巴斯', 1.25, 173),
('km', 'Comoros', 'جزر القمر', 'Komory', 'Komoren', 'Comoras', 'Comores', 'Comoren', 'コモロ', 'Comores', 'Comore', 'Коморские Острова', 'Comoros', '科摩羅', '科摩罗', -12.1, 44.15),
('kn', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس', 'Svatý Kitts a Nevis', 'St. Kitts und Nevis', 'San Cristóbal y Nieves', 'Saint-Kitts-et-Nevis', 'Saint Kitts en Nevis', 'セントクリストファー・ネイビス', 'Saint Kitts e Nevis', 'Saint Kitts e Nevis', 'Сент-Киттс и Невис', 'Saint Kitts and Nevis', '聖基茨和尼維斯', '圣基茨和尼维斯', 17.2, -62.45),
('kp', 'Korea, Democratic People’s Republic of (North)', 'كوريا الشمالية', 'Severní Korea', 'Demokratische Volksrepublik Korea', 'Corea del Norte', 'Corée du Nord', 'Noord-Korea', '朝鮮民主主義人民共和国', 'Coreia do Norte', 'Corea del Nord', 'Корейская Народно-Демократическая Республика', 'Korea (North)', '北韓', '北韩', 40, 127),
('kr', 'Korea, Republic of (South)', 'كوريا الجنوبية', 'Jižní Korea', 'Republik Korea', 'Corea del Sur', 'Corée du Sud', 'Zuid-Korea', '大韓民国', 'Coreia do Sul', 'Corea del Sud', 'Республика Корея', 'Korea (South)', '韓國', '韩国', 37, 127.3),
('kw', 'Kuwait', 'الكويت', 'Kuvajt', 'Kuwait', 'Kuwait', 'Koweït', 'Koeweit', 'クウェート', 'Cuaite', 'Kuwait', 'Кувейт', 'Kuwait', '科威特', '科威特', 29.3, 45.45),
('ky', 'Cayman Islands', 'جزر الكايمن', 'Kajmanské ostrovy', 'Kaimaninseln', 'Islas Caimán', 'Îles Caïmans', 'Caymaneilanden', 'ケイマン諸島', 'Ilhas Caimão', 'Isole Cayman', 'Каймановы острова', 'Cayman Islands', '開曼群島', '开曼群岛', 19.3, -80.3),
('kz', 'Kazakhstan', 'كازاخستان', 'Kazachstán', 'Kasachstan', 'Kazajistán', 'Kazakhstan', 'Kazachstan', 'カザフスタン', 'Cazaquistão', 'Kazakistan', 'Казахстан', 'Kazakhstan', '哈薩克斯坦', '哈萨克斯坦', 48, 68),
('la', 'Lao People’s Democratic Republic', 'لاوس', 'Lidově demokratická republika Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'ラオス', 'Laos, República Popular Democrática do', 'Laos', 'Лаос', 'Laos', '老撾', '老挝', 18, 105),
('lb', 'Lebanon', 'لبنان', 'Libanon', 'Libanon', 'Líbano', 'Liban', 'Libanon', 'レバノン', 'Líbano', 'Libano', 'Ливан', 'Lebanon', '黎巴嫩', '黎巴嫩', 33.5, 35.5),
('lc', 'Saint Lucia', 'سانت لوسيا', 'Svatá Lucie', 'St. Lucia', 'Santa Lucía', 'Sainte-Lucie', 'Saint Lucia', 'セントルシア', 'Santa Lúcia', 'Saint Lucia', 'Сент-Люсия', 'Saint Lucia', '聖盧西亞', '圣卢西亚', 13.53, -60.68),
('li', 'Liechtenstein', 'ليختنشتاين', 'Lichtenštejnsko', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'リヒテンシュタイン', 'Liechtenstein', 'Liechtenstein', 'Лихтенштейн', 'Liechtenstein', '列支敦士登', '列支敦士登', 47.16, 9.32),
('lk', 'Sri Lanka', 'سريلانكا', 'Srí Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'スリランカ', 'Sri Lanka', 'Sri Lanka', 'Шри-Ланка', 'Sri Lanka', '斯里蘭卡', '斯里兰卡', 7, 81),
('lr', 'Liberia', 'ليبيريا', 'Libérie', 'Liberia', 'Liberia', 'Libéria', 'Liberia', 'リベリア', 'Libéria', 'Liberia', 'Либерия', 'Liberia', '利比里亞', '利比里亚', 6.3, -9.3),
('ls', 'Lesotho', 'ليسوتو', 'Lesotho', 'Lesotho', 'Lesoto', 'Lesotho', 'Lesotho', 'レソト', 'Lesoto', 'Lesotho', 'Лесото', 'Lesotho', '萊索托', '莱索托', -29.3, 28.3),
('lt', 'Lithuania', 'ليتوانيا', 'Litva', 'Litauen', 'Lituania', 'Lituanie', 'Litouwen', 'リトアニア', 'Lituânia', 'Lituania', 'Литва', 'Lithuania', '立陶宛', '立陶宛', 56, 24),
('lu', 'Luxembourg', 'لوكسمبورج', 'Lucembursko', 'Luxemburg', 'Luxemburgo', 'Luxembourg', 'Luxemburg', 'ルクセンブルグ', 'Luxemburgo', 'Lussemburgo', 'Люксембург', 'Luxembourg', '盧森堡', '卢森堡', 49.45, 6.1),
('lv', 'Latvia', 'لاتفيا', 'Lotyšsko', 'Lettland', 'Letonia', 'Lettonie', 'Letland', 'ラトビア', 'Letónia', 'Lettonia', 'Латвия', 'Latvia', '拉脫維亞', '拉脱维亚', 57, 25),
('ly', 'Libyan Arab Jamahiriya', 'ليبيا', 'Libye', 'Libyen', 'Libia', 'Libye', 'Libië', 'リビア', 'Líbia', 'Libia', 'Ливия', 'Libya', '利比亞', '利比亚', 25, 17),
('ma', 'Morocco', 'المغرب', 'Maroko', 'Marokko', 'Marruecos', 'Maroc', 'Marokko', 'モロッコ', 'Marrocos', 'Marocco', 'Марокко', 'Morocco', '摩洛哥', '摩洛哥', 32, -5),
('mc', 'Monaco', 'موناكو', 'Monako', 'Monaco', 'Mónaco', 'Monaco', 'Monaco', 'モナコ', 'Mónaco', 'Monaco', 'Монако', 'Monaco', '摩納哥', '摩纳哥', 43.44, 7.24),
('md', 'Moldova', 'مولدافيا', 'Moldavsko, republika', 'Republik Moldau', 'Moldavia', 'Moldavie', 'Moldavië', 'モルドバ', 'Moldávia, República da', 'Moldavia', 'Молдова', 'Moldova', '摩爾多瓦', '摩尔多瓦', 47, 29),
('mg', 'Madagascar', 'مدغشقر', 'Madagaskar', 'Madagaskar', 'Madagascar', 'Madagascar', 'Madagaskar', 'マダガスカル', 'Madagáscar', 'Madagascar', 'Мадагаскар', 'Madagascar', '馬達加斯加', '马达加斯加', -20, 47),
('mh', 'Marshall Islands', 'جزر المارشال', 'Marshallovy ostrovy', 'Marshallinseln', 'Islas Marshall', 'Îles Marshall', 'Marshalleilanden', 'マーシャル諸島共和国', 'Ilhas Marshall', 'Isole Marshall', 'Маршалловы Острова', 'Marshall Islands', '馬紹爾群島', '马绍尔群岛', 9, 168),
('mk', 'Macedonia, the Former Yugoslav Republic of', 'مقدونيا', 'Macedonia', 'Mazedonien', 'Macedonia', 'Macédoine', 'Macedonië', 'マケドニア', 'Macedónia, República da', 'Repubblica di Macedonia', 'Македония', 'Macedonia', '馬其頓', '马其顿', 41.5, 22),
('ml', 'Mali', 'مالي', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'マリ', 'Mali', 'Mali', 'Мали', 'Mali', '馬里', '马里', 17, -4),
('mm', 'Myanmar', 'ميانمار', 'Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'ミャンマー', 'Mianmar', 'Myanmar', 'Мьянма', 'Burma (Myanmar)', '緬甸', '缅甸', 22, 98),
('mn', 'Mongolia', 'منغوليا', 'Mongolsko', 'Mongolei', 'Mongolia', 'Mongolie', 'Mongolië', 'モンゴル', 'Mongólia', 'Mongolia', 'Монголия', 'Mongolia', '蒙古', '蒙古', 46, 105),
('mo', 'Macau', 'ماكاو الصينية', 'Macao', 'Macao', 'Macao', 'Macao', 'Macao', 'マカオ', 'Macau', 'Macao', 'Макао', 'Macau', '澳門', '澳门', 22.1, 113.33),
('mp', 'Northern Mariana Islands', 'جزر ماريانا الشمالية', 'Severní Mariany', 'Nördliche Marianen', 'Islas Marianas del Norte', 'Îles Mariannes du Nord', 'Noordelijke Marianeneilanden', '北マリアナ諸島', 'Ilhas Mariana do Norte', 'Isole Marianne Settentrionali', 'Северные Марианские Острова', 'Northern Mariana Islands', '北馬里亞納群島', '北马里亚纳群岛', 15.12, 145.45),
('mq', 'Martinique', 'مارتينيك', 'Martinik', 'Martinique', 'Martinica', 'Martinique', 'Martinique', 'マルティニーク島', 'Martinica', 'Martinica', 'Мартиник', 'Martinique', '馬提尼克島', '马提尼克岛', 14.4, -61),
('mr', 'Mauritania', 'موريتانيا', 'Mauritánie', 'Mauretanien', 'Mauritania', 'Mauritanie', 'Mauritanië', 'モーリタニア', 'Mauritânia', 'Mauritania', 'Мавритания', 'Mauritania', '毛里塔尼亞', '毛里塔尼亚', 20, -12),
('ms', 'Montserrat', 'مونتسرات', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'モントセラト島', 'Monserrate', 'Montserrat', 'Монсеррат', 'Montserrat', '蒙特塞拉特', '蒙特塞拉特', 16.45, -62.12),
('mt', 'Malta', 'مالطا', 'Malta', 'Malta', 'Malta', 'Malte', 'Malta', 'マルタ', 'Malta', 'Malta', 'Мальта', 'Malta', '馬耳他', '马耳他', 35.5, 14.35),
('mu', 'Mauritius', 'موريشيوس', 'Mauricius', 'Mauritius', 'Mauricio', 'Maurice', 'Mauritius', 'モーリシャス', 'Maurícias', 'Mauritius', 'Маврикий', 'Mauritius', '毛里求斯', '毛里求斯', -20.17, 57.33),
('mv', 'Maldives', 'جزر الملديف', 'Maladivy', 'Malediven', 'Maldivas', 'Maldives', 'Maldiven', 'モルジブ', 'Maldivas', 'Maldive', 'Мальдивы', 'Maldives', '馬爾代夫', '马尔代夫', 3.15, 73),
('mw', 'Malawi', 'ملاوي', 'Malawi', 'Malawi', 'Malaui', 'Malawi', 'Malawi', 'マラウィ', 'Malaui', 'Malawi', 'Малави', 'Malawi', '馬拉維', '马拉维', -13.3, 34),
('mx', 'Mexico', 'المكسيك', 'Mexiko', 'Mexiko', 'México', 'Mexique', 'Mexico', 'メキシコ', 'México', 'Messico', 'Мексика', 'Mexico', '墨西哥', '墨西哥', 23, -102),
('my', 'Malaysia', 'ماليزيا', 'Malajsie', 'Malaysia', 'Malasia', 'Malaisie', 'Maleisië', 'マレーシア', 'Malásia', 'Malesia', 'Малайзия', 'Malaysia', '馬來西亞', '马来西亚', 2.3, 112.3),
('mz', 'Mozambique', 'موزمبيق', 'Mosambik', 'Mosambik', 'Mozambique', 'Mozambique', 'Mozambique', 'モザンビーク', 'Moçambique', 'Mozambico', 'Мозамбик', 'Mozambique', '莫桑比克', '莫桑比克', -18.15, 35),
('na', 'Namibia', 'ناميبيا', 'Namibie', 'Namibia', 'Namibia', 'Namibie', 'Namibië', 'ナミビア', 'Namíbia', 'Namibia', 'Намибия', 'Namibia', '納米比亞', '纳米比亚', -22, 17),
('nc', 'New Caledonia', 'كاليدونيا الجديدة', 'Nová Kaledonie', 'Neukaledonien', 'Nueva Caledonia', 'Nouvelle-Calédonie', 'Nieuw-Caledonië', 'ニューカレドニア', 'Nova Caledónia', 'Nuova Caledonia', 'Новая Каледония', 'New Caledonia', '新喀裡多尼亞', '新喀里多尼亚', -21.3, 165.3),
('ne', 'Niger', 'النيجر', 'Niger', 'Niger', 'Níger', 'Niger', 'Niger', 'ニジェール', 'Níger', 'Niger', 'Нигер', 'Niger', '尼日爾', '尼日尔', 16, 8),
('nf', 'Norfolk Island', 'جزيرة نورفوك', 'Norfolk', 'Norfolkinsel', 'Isla Norfolk', 'Île Norfolk', 'Norfolkeiland', 'ノーフォーク島', 'Ilha Norfolque', 'Isola Norfolk', 'Остров Норфолк', 'Norfolk Island', '諾福克島', '诺福克岛', -29.02, 167.57),
('ng', 'Nigeria', 'نيجيريا', 'Nigérie', 'Nigeria', 'Nigeria', 'Nigéria', 'Nigeria', 'ナイジェリア', 'Nigéria', 'Nigeria', 'Нигерия', 'Nigeria', '尼日利亞', '尼日利亚', 10, 8),
('ni', 'Nicaragua', 'نيكاراجوا', 'Nikaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'ニカラグア', 'Nicarágua', 'Nicaragua', 'Никарагуа', 'Nicaragua', '尼加拉瓜', '尼加拉瓜', 13, -85),
('nl', 'Netherlands', 'هولندا', 'Nizozemsko', 'Niederlande', 'Países Bajos', 'Pays-Bas', 'Nederland', 'オランダ', 'Países Baixos', 'Paesi Bassi', 'Нидерланды', 'Netherlands', '荷蘭', '荷兰', 52.3, 5.45),
('no', 'Norway', 'النرويج', 'Norsko', 'Norwegen', 'Noruega', 'Norvège', 'Noorwegen', 'ノルウェー', 'Noruega', 'Norvegia', 'Норвегия', 'Norway', '挪威', '挪威', 62, 10),
('np', 'Nepal', 'نيبال', 'Nepál', 'Nepal', 'Nepal', 'Népal', 'Nepal', 'ネパール', 'Nepal', 'Nepal', 'Непал', 'Nepal', '尼泊爾', '尼泊尔', 28, 84),
('nr', 'Nauru', 'نورو', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'ナウル', 'Nauru', 'Nauru', 'Науру', 'Nauru', '瑙魯', '瑙鲁', -0.32, 166.55),
('nt', 'Neutral Zone', 'المنطقة المحايدة', 'neutrální zóna', 'Neutral Zone', 'zona neutral', 'zone neutre', 'neutrale zone', '中立地帯', 'zona neutra', 'zona neutra', 'Нейтральная зона', 'Neutral Zone', '中立區', '中立区', 0, 0),
('nu', 'Niue', 'نيوي', 'Niue', 'Niue', 'Isla Niue', 'Niue', 'Niue', 'ニウエ島', 'Niue', 'Niue', 'Ниуе', 'Niue', '紐埃', '纽埃', -19.02, -169.52),
('nz', 'New Zealand', 'نيوزيلاندا', 'Nový Zéland', 'Neuseeland', 'Nueva Zelanda', 'Nouvelle-Zélande', 'Nieuw-Zeeland', 'ニュージーランド', 'Nova Zelândia', 'Nuova Zelanda', 'Новая Зеландия', 'New Zealand (Aotearoa)', '新西蘭', '新西兰', -41, 174),
('om', 'Oman', 'عمان', 'Omán', 'Oman', 'Omán', 'Oman', 'Oman', 'オマーン', 'Omã', 'Oman', 'Оман', 'Oman', '阿曼', '阿曼', 21, 57),
('pa', 'Panama', 'بنما', 'Panama', 'Panama', 'Panamá', 'Panama', 'Panama', 'パナマ', 'Panamá', 'Panama', 'Панама', 'Panama', '巴拿馬', '巴拿马', 9, -80),
('pe', 'Peru', 'بيرو', 'Peru', 'Peru', 'Perú', 'Pérou', 'Peru', 'ペルー', 'Peru', 'Perù', 'Перу', 'Peru', '秘魯', '秘鲁', -10, -76),
('pf', 'French Polynesia', 'بولينيزيا الفرنسية', 'Francouzská Polynésie', 'Französisch-Polynesien', 'Polinesia Francesa', 'Polynésie française', 'Frans-Polynesië', '仏領ポリネシア', 'Polinésia Francesa', 'Polinesia Francese', 'Французская Полинезия', 'French Polynesia', '法屬波利尼西亞', '法属波利尼西亚', -15, -140),
('pg', 'Papua New Guinea', 'بابوا غينيا الجديدة', 'Papua-Nová Guinea', 'Papua-Neuguinea', 'Papúa Nueva Guinea', 'Papouasie-Nouvelle-Guinée', 'Papoea-Nieuw-Guinea', 'パプアニューギニア', 'Papua Nova Guiné', 'Papua Nuova Guinea', 'Папуа-Новая Гвинея', 'Papua New Guinea', '巴布亞新幾內亞', '巴布亚新几内亚', -6, 147),
('ph', 'Philippines', 'الفيلبين', 'Filipíny', 'Philippinen', 'Filipinas', 'Philippines', 'Filipijnen', 'フィリピン', 'Filipinas', 'Filippine', 'Филиппины', 'Philippines', '菲律賓', '菲律宾', 13, 122),
('pk', 'Pakistan', 'باكستان', 'Pákistán', 'Pakistan', 'Pakistán', 'Pakistan', 'Pakistan', 'パキスタン', 'Paquistão', 'Pakistan', 'Пакистан', 'Pakistan', '巴基斯坦', '巴基斯坦', 30, 70),
('pl', 'Poland', 'بولندا', 'Polsko', 'Polen', 'Polonia', 'Pologne', 'Polen', 'ポーランド', 'Polónia', 'Polonia', 'Польша', 'Poland', '波蘭', '波兰', 52, 20),
('pm', 'Saint Pierre and Miquelon', 'سانت بيير وميكولون', 'Svatý Pierre a Miquelon', 'St. Pierre und Miquelon', 'San Pedro y Miquelón', 'Saint-Pierre-et-Miquelon', 'Saint Pierre en Miquelon', 'サンピエール島・ミクロン島', 'Saint Pierre e Miquelon', 'Saint Pierre e Miquelon', 'Сен-Пьер и Микелон', 'St. Pierre and Miquelon', '聖皮埃爾和密克隆', '圣皮埃尔和密克隆', 46.5, -56.2),
('pn', 'Pitcairn', 'بتكايرن', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'ピトケアン島', 'Pitcairn', 'Pitcairn', 'Питкерн', 'Pitcairn', '皮特凱恩', '皮特凯恩', -25.04, -130.06),
('pr', 'Puerto Rico', 'بورتوريكو', 'Portoriko', 'Puerto Rico', 'Puerto Rico', 'Porto Rico', 'Puerto Rico', 'プエルトリコ', 'Porto Rico', 'Portorico', 'Пуэрто-Рико', 'Puerto Rico', '波多黎各', '波多黎各', 18.15, -66.3),
('pt', 'Portugal', 'البرتغال', 'Portugalsko', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'ポルトガル', 'Portugal', 'Portogallo', 'Португалия', 'Portugal', '葡萄牙', '葡萄牙', 39.3, -8),
('pw', 'Palau', 'بالاو', 'Palau', 'Palau', 'Palau', 'Palaos', 'Palau', 'パラオ', 'Palau', 'Palau', 'Палау', 'Palau', '帕勞', '帕劳', 7.3, 134.3),
('py', 'Paraguay', 'باراجواي', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'パラグアイ', 'Paraguai', 'Paraguay', 'Парагвай', 'Paraguay', '巴拉圭', '巴拉圭', -23, -58),
('qa', 'Qatar', 'قطر', 'Katar', 'Katar', 'Qatar', 'Qatar', 'Qatar', 'カタール', 'Qatar', 'Qatar', 'Катар', 'Qatar', '卡塔爾', '卡塔尔', 25.3, 51.15),
('re', 'Reunion', 'روينيون', 'Réunion', 'Réunion', 'Reunión', 'Réunion', 'Réunion', 'レユニオン島', 'Reunião', 'Réunion', 'Реюньон', 'Reunion', '團圓', '团圆', -21.06, 55.36),
('ro', 'Romania', 'رومانيا', 'Rumunsko', 'Rumänien', 'Rumanía', 'Roumanie', 'Roemenië', 'ルーマニア', 'Roménia', 'Romania', 'Румыния', 'Romania', '羅馬尼亞', '罗马尼亚', 46, 25),
('ru', 'Russian Federation', 'روسيا', 'Rusko', 'Russische Föderation', 'Rusia', 'Russie', 'Rusland', 'ロシア', 'Rússia', 'Federazione Russa', 'Россия', 'Russia', '俄國', '俄国', 60, 100),
('rw', 'Rwanda', 'رواندا', 'Rwanda', 'Ruanda', 'Ruanda', 'Rwanda', 'Rwanda', 'ルワンダ', 'Ruanda', 'Ruanda', 'Руанда', 'Rwanda', '盧旺達', '卢旺达', -2, 30),
('sa', 'Saudi Arabia', 'المملكة العربية السعودية', 'Saúdská Arábie', 'Saudi-Arabien', 'Arabia Saudí', 'Arabie saoudite', 'Saoedi-Arabië', 'サウジアラビア', 'Arábia Saudita', 'Arabia Saudita', 'Саудовская Аравия', 'Saudi Arabia', '沙特阿拉伯', '沙特阿拉伯', 25, 45),
('sb', 'Solomon Islands', 'جزر سليمان', 'Šalamounovy ostrovy', 'Salomonen', 'Islas Salomón', 'Îles Salomon', 'Salomonseilanden', 'ソロモン諸島', 'Ilhas Salomão', 'Isole Solomon', 'Соломоновы Острова', 'Solomon Islands', '索羅門群島', '索罗门群岛', -8, 159),
('sc', 'Seychelles', 'سيشل', 'Seychely', 'Seychellen', 'Seychelles', 'Seychelles', 'Seychellen', 'セーシェル', 'Seicheles', 'Seychelles', 'Сейшельские Острова', 'Seychelles', '塞舌爾', '塞舌尔', -4.35, 55.4),
('sd', 'Sudan', 'السودان', 'Súdán', 'Sudan', 'Sudán', 'Soudan', 'Soedan', 'スーダン', 'Sudão', 'Sudan', 'Судан', 'Sudan', '蘇丹', '苏丹', 15, 30),
('se', 'Sweden', 'السويد', 'Švédsko', 'Schweden', 'Suecia', 'Suède', 'Zweden', 'スウェーデン', 'Suécia', 'Svezia', 'Швеция', 'Sweden', '瑞典', '瑞典', 62, 15),
('sg', 'Singapore', 'سنغافورة', 'Singapur', 'Singapur', 'Singapur', 'Singapour', 'Singapore', 'シンガポール', 'Singapura', 'Singapore', 'Сингапур', 'Singapore', '新加坡', '新加坡', 1.22, 103.48),
('sh', 'Saint Helena', 'سانت هيلنا', 'Svatá Helena', 'St. Helena', 'Santa Elena', 'Sainte-Hélène', 'Sint-Helena', 'セントヘレナ', 'Santa Helena', 'Sant’Elena', 'Остров Святой Елены', 'St. Helena', '聖赫勒拿島', '圣赫勒拿岛', -15.56, -5.42),
('si', 'Slovenia', 'سلوفينيا', 'Slovinsko', 'Slowenien', 'Eslovenia', 'Slovénie', 'Slovenië', 'スロベニア', 'Eslovénia', 'Slovenia', 'Словения', 'Slovenia', '斯洛文尼亞', '斯洛文尼亚', 46.07, 14.49),
('sj', 'Svalbard and Jan Mayen Islands', 'سفالبارد وجان مايان', 'Svalbard a Jan Mayen', 'Svalbard und Jan Mayen', 'Svalbard y Jan Mayen', 'Svalbard et Île Jan Mayen', 'Svalbard en Jan Mayen', 'スバールバル諸島・ヤンマイエン島', 'Esvalbarda e Jan Mayen', 'Svalbard e Jan Mayen', 'Свальбард и Ян-Майен', 'Svalbard and Jan Mayen Islands', '斯瓦爾巴群島和揚馬延島', '斯瓦尔巴群岛和扬马延岛', 78, 20),
('sk', 'Slovakia', 'سلوفاكيا', 'Slovensko', 'Slowakei', 'Eslovaquia', 'Slovaquie', 'Slowakije', 'スロバキア', 'Eslováquia', 'Slovacchia', 'Словакия', 'Slovak Republic', '斯洛伐克', '斯洛伐克', 48.4, 19.3),
('sl', 'Sierra Leone', 'سيراليون', 'Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'Sierra Leone', 'Sierra Leone', 'シエラレオネ', 'Serra Leoa', 'Sierra Leone', 'Сьерра-Леоне', 'Sierra Leone', '塞拉利昂', '塞拉利昂', 8.3, -11.3),
('sm', 'San Marino', 'سان مارينو', 'San Marino', 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino', 'サンマリノ', 'São Marino', 'San Marino', 'Сан-Марино', 'San Marino', '聖馬力諾', '圣马力诺', 43.46, 12.25),
('sn', 'Senegal', 'السنغال', 'Senegal', 'Senegal', 'Senegal', 'Sénégal', 'Senegal', 'セネガル', 'Senegal', 'Senegal', 'Сенегал', 'Senegal', '塞內加爾', '塞内加尔', 14, -14),
('so', 'Somalia', 'الصومال', 'Somálsko', 'Somalia', 'Somalia', 'Somalie', 'Somalië', 'ソマリア', 'Somália', 'Somalia', 'Сомали', 'Somalia', '索馬里', '索马里', 10, 49),
('sr', 'Suriname', 'سورينام', 'Surinam', 'Suriname', 'Surinam', 'Suriname', 'Suriname', 'スリナム', 'Suriname', 'Suriname', 'Суринам', 'Suriname', '蘇里南', '苏里南', 4, -56),
('st', 'Sao Tome and Principe', 'ساو تومي وبرينسيبي', 'Svatý Tomáš', 'São Tomé und Príncipe', 'Santo Tomé y Príncipe', 'Sao Tomé-et-Principe', 'Sao Tomé en Principe', 'サントメ・プリンシペ', 'São Tomé e Príncipe', 'Sao Tomé e Príncipe', 'Сан-Томе и Принсипи', 'Sao Tome and Principe', '聖多美和普林西比', '圣多美和普林西比', 1, 7),
('sv', 'El Salvador', 'السلفادور', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'エルサルバドル', 'El Salvador', 'El Salvador', 'Сальвадор', 'El Salvador', '薩爾瓦多', '萨尔瓦多', 13.5, -88.55),
('sy', 'Syrian Arab Republic', 'سوريا', 'Sýrie', 'Syrien', 'Siria', 'Syrie', 'Syrië', 'シリア', 'Síria', 'Siria', 'Сирийская Арабская Республика', 'Syrian Arab Republic', '敘利亞', '叙利亚', 35, 38),
('sz', 'Swaziland', 'سوازيلاند', 'Svazijsko', 'Swasiland', 'Suazilandia', 'Swaziland', 'Swaziland', 'スワジランド', 'Suazilândia', 'Swaziland', 'Свазиленд', 'Swaziland', '斯威士蘭', '斯威士兰', -26.3, 31.3),
('tc', 'Turks and Caicos Islands', 'جزر الترك وجايكوس', 'Ostrovy Caicos a Turks', 'Turks- und Caicosinseln', 'Islas Turcas y Caicos', 'Îles Turks et Caïques', 'Turks- en Caicoseilanden', 'タークス諸島・カイコス諸島', 'Ilhas Turcas e Caicos', 'Isole Turks e Caicos', 'Острова Тёркс и Кайкос', 'Turks and Caicos Islands', '特克斯和凱科斯群島', '特克斯和凯科斯群岛', 21.45, -71.35),
('td', 'Chad', 'تشاد', 'Čad', 'Tschad', 'Chad', 'Tchad', 'Tsjaad', 'チャド', 'Chade', 'Ciad', 'Чад', 'Chad', '乍得', '乍得', 15, 19),
('tf', 'French Southern Territories', 'المقاطعات الجنوبية الفرنسية', 'Francouzská jižní teritoria', 'Französische Süd- und Antarktisgebiete', 'Territorios Australes Franceses', 'Terres australes françaises', 'Franse Gebieden in de zuidelijke Indische Oceaan', 'フランス領極南諸島', 'Territórios Franceses do Sul', 'Territori australi francesi', 'Французские Южные Территории', 'French Southern Territories', '法國南部領土', '法国南部领土', -43, 67),
('tg', 'Togo', 'توجو', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'トーゴ', 'Togo', 'Togo', 'Того', 'Togo', '多哥', '多哥', 8, 1.1),
('th', 'Thailand', 'تايلند', 'Thajsko', 'Thailand', 'Tailandia', 'Thaïlande', 'Thailand', 'タイ', 'Tailândia', 'Tailandia', 'Таиланд', 'Thailand', '泰國', '泰国', 15, 100),
('tj', 'Tajikistan', 'طاجكستان', 'Tádžikistán', 'Tadschikistan', 'Tayikistán', 'Tadjikistan', 'Tadzjikistan', 'タジキスタン', 'Tajiquistão', 'Tagikistan', 'Таджикистан', 'Tajikistan', '塔吉克斯坦', '塔吉克斯坦', 39, 71);
INSERT INTO `countries` (`code`, `iso_country`, `country_ar_SA`, `country_cs_CZ`, `country_de_DE`, `country_es_ES`, `country_fr_FR`, `country_nl_NL`, `country_ja_JP`, `country_pt_PT`, `country_it_IT`, `country_ru_RU`, `country_en_GB`, `country_zh_TW`, `country_zh_CN`, `lat`, `lon`) VALUES
('tk', 'Tokelau', 'توكيلو', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'トケラウ諸島', 'Toquelau', 'Tokelau', 'Токелау', 'Tokelau', '托克勞', '托克劳', -9, -172),
('tm', 'Turkmenistan', 'تركمانستان', 'Turkmenistán', 'Turkmenistan', 'Turkmenistán', 'Turkménistan', 'Turkmenistan', 'トルクメニスタン', 'Turquemenistão', 'Turkmenistan', 'Туркменистан', 'Turkmenistan', '土庫曼斯坦', '土库曼斯坦', 40, 60),
('tn', 'Tunisia', 'تونس', 'Tunisko', 'Tunesien', 'Túnez', 'Tunisie', 'Tunesië', 'チュニジア', 'Tunísia', 'Tunisia', 'Тунис', 'Tunisia', '突尼斯', '突尼斯', 34, 9),
('to', 'Tonga', 'تونجا', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'トンガ', 'Tonga', 'Tonga', 'Тонга', 'Tonga', '湯加', '汤加', -20, -175),
('tl', 'Timor-Leste', 'تيمور الشرقية', 'Východní Timor', 'Osttimor', 'Timor Oriental', 'Timor oriental', 'Oost-Timor', '東ティモール', 'Timor Leste', 'Timor Est', 'Восточный Тимор', 'East Timor', '東帝汶', '东帝汶', -8.5, 125.55),
('tr', 'Turkey', 'تركيا', 'Turecko', 'Türkei', 'Turquía', 'Turquie', 'Turkije', 'トルコ', 'Turquia', 'Turchia', 'Турция', 'Turkey', '土耳其', '土耳其', 39, 35),
('tt', 'Trinidad and Tobago', 'ترينيداد وتوباغو', 'Trinidad a Tobago', 'Trinidad und Tobago', 'Trinidad y Tobago', 'Trinité-et-Tobago', 'Trinidad en Tobago', 'トリニダード・トバゴ', 'Trindade e Tobago', 'Trinidad e Tobago', 'Тринидад и Тобаго', 'Trinidad and Tobago', '特里尼達和多巴哥', '特里尼达和多巴哥', 11, -61),
('tv', 'Tuvalu', 'توفالو', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'ツバル', 'Tuvalu', 'Tuvalu', 'Тувалу', 'Tuvalu', '圖瓦盧', '图瓦卢', -8, 178),
('tw', 'Taiwan', 'تايوان', 'Tchaj-wan', 'Taiwan', 'Taiwán', 'Taïwan', 'Taiwan', '台湾', 'Taiwan', 'Taiwan', 'Тайвань', 'Taiwan', '台灣', '台湾', 23.3, 121),
('tz', 'Tanzania, United Republic of', 'تانزانيا', 'Tanzanie', 'Tansania', 'Tanzania', 'Tanzanie', 'Tanzania', 'タンザニア', 'Tanzânia', 'Tanzania', 'Танзания', 'Tanzania', '坦桑尼亞', '坦桑尼亚', -6, 35),
('ua', 'Ukraine', 'أوكرانيا', 'Ukrajina', 'Ukraine', 'Ucrania', 'Ukraine', 'Oekraïne', 'ウクライナ', 'Ucrânia', 'Ucraina', 'Украина', 'Ukraine', '烏克蘭', '乌克兰', 49, 32),
('ug', 'Uganda', 'أوغندا', 'Uganda', 'Uganda', 'Uganda', 'Ouganda', 'Oeganda', 'ウガンダ', 'Uganda', 'Uganda', 'Уганда', 'Uganda', '烏干達', '乌干达', 1, 32),
('uk', 'United Kingdom', 'بريطانيا العظمي', 'Velká Británie', 'Großbritannien', 'Gran Bretaña', 'Grande-Bretagne', 'Groot-Brittannië', 'グレート·ブリテン', 'Grã-Bretanha', 'Gran Bretagna', 'Великобритания', 'United Kingdom', '英國', '英国', 54, -2),
('us', 'United States', 'الولايات المتحدة الأمريكية', 'Spojené státy', 'Vereinigte Staaten', 'Estados Unidos', 'États-Unis', 'Verenigde Staten', 'アメリカ合衆国', 'Estados Unidos', 'Stati Uniti', 'США', 'United States', '美國', '美国', 38, -97),
('uy', 'Uruguay', 'أورجواي', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'ウルグアイ', 'Uruguai', 'Uruguay', 'Уругвай', 'Uruguay', '烏拉圭', '乌拉圭', -33, -56),
('uz', 'Uzbekistan', 'أوزبكستان', 'Uzbekistán', 'Usbekistan', 'Uzbekistán', 'Ouzbékistan', 'Oezbekistan', 'ウズベキスタン', 'Usbequistão', 'Uzbekistan', 'Узбекистан', 'Uzbekistan', '烏茲別克斯坦', '乌兹别克斯坦', 41, 64),
('va', 'Vatican City State', 'الفاتيكان', 'Svatý stolec', 'Vatikanstadt', 'Ciudad del Vaticano', 'État de la Cité du Vatican', 'Vaticaanstad', 'バチカン市国', 'Vaticano', 'Vaticano', 'Ватикан', 'Vatican City State (Holy See)', '教廷', '教廷', 41.54, 12.27),
('vc', 'Saint Vincent and the Grenadines', 'سانت فنسنت وغرنادين', 'Svatý Vincent a Grenadiny', 'St. Vincent und die Grenadinen', 'San Vicente y las Granadinas', 'Saint-Vincent-et-les Grenadines', 'Saint Vincent en de Grenadines', 'セントビンセント・グレナディーン諸島', 'São Vicente e Granadinas', 'Saint Vincent e Grenadines', 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', '聖文森特和格林納丁斯', '圣文森特和格林纳丁斯', 13.15, -61.12),
('ve', 'Venezuela', 'فنزويلا', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'ベネズエラ', 'Venezuela', 'Venezuela', 'Венесуэла', 'Venezuela', '委內瑞拉', '委内瑞拉', 8, -66),
('vg', 'Virgin Islands, British', 'جزر فرجين البريطانية', 'Britské Panenské ostrovy', 'Britische Jungferninseln', 'Islas Vírgenes Británicas', 'Îles Vierges britanniques', 'Britse Maagdeneilanden', 'イギリス領ヴァージン諸島', 'Ilhas Virgens Britânicas', 'Isole Vergini Britanniche', 'Британские Виргинские Острова', 'Virgin Islands (British)', '英屬維爾京群島', '英属维尔京群岛', 18.2, -64.5),
('vi', 'Virgin Islands, U.S.', 'جزر فرجين الأمريكية', 'Americké Panenské ostrovy', 'Amerikanische Jungferninseln', 'Islas Vírgenes de los Estados Unidos', 'Îles Vierges des États-Unis', 'Amerikaanse Maagdeneilanden', 'アメリカ領ヴァージン諸島', 'Ilhas Virgin E.U.A.', 'Isole Vergini Americane', 'Американские Виргинские острова', 'Virgin Islands (U.S.)', '美國維爾京群島', '美国维尔京群岛', 18.2, -64.5),
('vn', 'Viet Nam', 'فيتنام', 'Vietnam', 'Vietnam', 'Vietnam', 'Viêt Nam', 'Vietnam', 'ベトナム', 'Vietname', 'Vietnam', 'Вьетнам', 'Viet Nam', '越南', '越南', 16, 106),
('vu', 'Vanuatu', 'فانواتو', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'バヌアツ', 'Vanuatu', 'Vanuatu', 'Вануату', 'Vanuatu', '瓦努阿圖', '瓦努阿图', -16, 167),
('wf', 'Wallis and Futuna Islands', 'جزر والس وفوتونا', 'Wallis a Futuna', 'Wallis und Futuna', 'Wallis y Futuna', 'Wallis-et-Futuna', 'Wallis en Futuna', 'ウォリス・フツナ', 'Wallis e Futuna', 'Wallis e Futuna', 'Уоллис и Футуна', 'Wallis and Futuna Islands', '瓦利斯群島和富圖納群島', '瓦利斯群岛和富图纳群岛', -13.18, -176.12),
('ws', 'Samoa', 'ساموا', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'サモア', 'Samoa', 'Samoa', 'Самоа', 'Samoa', '薩摩亞', '萨摩亚', -13.35, -172.2),
('ye', 'Yemen', 'اليمن', 'Jemen', 'Jemen', 'Yemen', 'Yémen', 'Jemen', 'イエメン', 'Iémen', 'Yemen', 'Йемен', 'Yemen', '也門', '也门', 15, 48),
('yt', 'Mayotte', 'مايوت', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'マヨット島', 'Mayotte', 'Mayotte', 'Майотта', 'Mayotte', '馬約特島', '马约特岛', -12.5, 45.1),
('yu', 'Yugoslavia', 'يوغوسلافيا', 'Jugoslávie', 'Jugoslawien', 'Yugoslavia', 'Yougoslavie', 'Joegoslavië', 'ユーゴスラビア', 'Iugoslávia', 'Jugoslavia', 'Югославия', 'Yugoslavia', '南斯拉夫', '南斯拉夫', 44, 21),
('za', 'South Africa', 'جمهورية جنوب افريقيا', 'Jihoafrická republika', 'Südafrika', 'Sudáfrica', 'Afrique du Sud', 'Zuid-Afrika', '南アフリカ', 'África do Sul', 'Sudafrica', 'Южная Африка', 'South Africa', '南非', '南非', -29, 24),
('zm', 'Zambia', 'زامبيا', 'Zambie', 'Sambia', 'Zambia', 'Zambie', 'Zambia', 'ザンビア', 'Zâmbia', 'Zambia', 'Замбия', 'Zambia', '贊比亞', '赞比亚', -15, 30),
('cd', 'Congo, Democratic Republic of the', 'جمهورية الكونغو الديمقراطية', 'Demokratická republika Kongo', 'Demokratische Republik Kongo', 'República Democrática del Congo', 'République démocratique du Congo', 'Congo-Kinshasa', 'コンゴ民主共和国 (キンシャサ)', 'República Democrática do Congo', 'Repubblica Democratica del Congo', 'Демократическая Республика Конго', 'Democratic Republic of Congo', '剛果民主共和國', '刚果民主共和国', -4.04, 30.75),
('zw', 'Zimbabwe', 'زيمبابوي', 'Zimbabwe', 'Simbabwe', 'Zimbabue', 'Zimbabwe', 'Zimbabwe', 'ジンバブエ', 'Zimbabwe', 'Zimbabwe', 'Зимбабве', 'Zimbabwe', '津巴布韋', '津巴布韦', -20, 30),
('ap', '', 'آسيا والمحيط الهادئ', 'Asie a Tichomoří', 'Asien-Pazifik', 'Asia y el Pacífico', 'Asie-Pacifique', 'Asia-Pacific', 'アジア太平洋', 'Ásia-Pacífico', 'Asia-Pacifico', 'Азиатско-Тихоокеанский', 'Asia-Pacific', '亞太', '亚太', -2.81, 128.5),
('rs', 'Serbia', 'صربيا', 'Srbsko', 'Serbien', 'Serbia', 'Serbie', 'Servië', 'セルビア', 'Sérvia', 'Serbia', 'Сербия', 'Republic of Serbia', '塞爾維亞', '塞尔维亚', 44.02, 21.01),
('ax', 'Aland Islands', 'جزر أولان', 'Alandy', 'Alandinseln', 'Islas Åland', 'Îles Åland', 'Alandeilanden', 'オーランド諸島', 'Ilhas Alanda', 'Isole Aland', 'Аландские острова', 'Åland Islands', '奧蘭群島', '奥兰群岛', 60.21, 20.16),
('eu', '', 'أوروبا', 'Evropa', 'Europa', 'Europa', 'Europe', 'Europa', 'ヨーロッパ', 'Europa', 'Europa', 'Европа', 'Europe', '歐洲', '欧洲', 50, 15),
('01', '', 'الشخصية', 'soukromá', 'privat', 'privada', 'privé', 'privaat', 'プライベート', 'privada', 'privato', 'личный', 'Private', '私有', '私有', 0, 0),
('ps', 'Palestinian Territory, Occupied', 'فلسطين', 'Palestinian Territory', 'Palästinensische Gebiete', 'Palestina', 'Territoire palestinien', 'Palestijns Gebied', 'パレスチナ領土', 'Território Palestiniano', 'Palestina', 'Палестинская автономия', 'Palestinian Territory, Occupied', '巴勒斯坦', '巴勒斯坦', 31.89, 34.9),
('me', 'Montenegro', 'الجبل الأسود', 'Černá Hora', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro', 'モンテネグロ', 'Montenegro', 'Montenegro', 'Черногория', 'Montenegro', '黑山', '黑山', 42.74, 19.31);


