--
-- Countries
-- Copyright (c) 2012 Peter Kahl. All rights reserved.
-- Use of this source code is governed by a GNU General Public License
-- that can be found in the LICENSE file.
--
-- https://github.com/peterkahl/countries
--

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


-- --------------------------------------------------------

--
-- Table structure for table `countries`
--

CREATE TABLE IF NOT EXISTS `countries` (
  `code` varchar(4) NOT NULL DEFAULT '',
  `iso_country` varchar(255) NOT NULL DEFAULT '',
  `country_en_GB` varchar(255) NOT NULL DEFAULT '',
  `country_zh_TW` varchar(255) NOT NULL,
  `country_zh_CN` varchar(255) NOT NULL,
  `lat` float NOT NULL DEFAULT '0',
  `lon` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`code`),
  KEY `code` (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `countries`
--

INSERT INTO `countries` (`code`, `iso_country`, `country_en_GB`, `country_zh_TW`, `country_zh_CN`, `lat`, `lon`) VALUES
('ad', 'Andorra', 'Andorra', '安道爾', '安道尔', 42.3, 1.3),
('ae', 'United Arab Emirates', 'United Arab Emirates', '阿拉伯聯合大公國', '阿拉伯联合大公国', 24, 54),
('af', 'Afghanistan', 'Afghanistan', '阿富汗', '阿富汗', 33, 65),
('ag', 'Antigua and Barbuda', 'Antigua and Barbuda', '安提瓜和巴布達', '安提瓜和巴布达', 17.03, -61.48),
('ai', 'Anguilla', 'Anguilla', '安圭拉', '安圭拉', 18.15, -63.1),
('al', 'Albania', 'Albania', '阿爾巴尼亞', '阿尔巴尼亚', 41, 20),
('am', 'Armenia', 'Armenia', '亞美尼亞', '亚美尼亚', 40, 45),
('an', 'Netherlands Antilles', 'Netherlands Antilles', '荷屬安的列斯群島', '荷属安的列斯群岛', 12.15, -68.45),
('ao', 'Angola', 'Angola', '安哥拉', '安哥拉', -12.3, 18.3),
('aq', 'Antarctica', 'Antarctica', '南極洲', '南极洲', -90, 0),
('ar', 'Argentina', 'Argentina', '阿根廷', '阿根廷', -34, -64),
('as', 'American Samoa', 'American Samoa', '美屬薩摩亞', '美属萨摩亚', -14.2, -170),
('at', 'Austria', 'Austria', '奧地利', '奥地利', 47.2, 13.2),
('au', 'Australia', 'Australia', '澳大利亞', '澳大利亚', -27, 133),
('aw', 'Aruba', 'Aruba', '阿魯巴', '阿鲁巴', 12.3, -69.58),
('az', 'Azerbaijan', 'Azerbaijan', '阿塞拜疆', '阿塞拜疆', 40.3, 47.3),
('ba', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', '波斯尼亞和黑塞哥維那', '波斯尼亚和黑塞哥维那', 44, 18),
('bb', 'Barbados', 'Barbados', '巴巴多斯', '巴巴多斯', 13.1, -59.32),
('bd', 'Bangladesh', 'Bangladesh', '孟加拉國', '孟加拉国', 24, 90),
('be', 'Belgium', 'Belgium', '比利時', '比利时', 50.5, 4),
('bf', 'Burkina Faso', 'Burkina Faso', '布基納法索', '布基纳法索', 13, -2),
('bg', 'Bulgaria', 'Bulgaria', '保加利亞', '保加利亚', 43, 25),
('bh', 'Bahrain', 'Bahrain', '巴林', '巴林', 26, 50.33),
('bi', 'Burundi', 'Burundi', '布隆迪', '布隆迪', -3.3, 30),
('bj', 'Benin', 'Benin', '貝寧', '贝宁', 9.3, 2.15),
('bm', 'Bermuda', 'Bermuda', '百慕大', '百慕大', 32.2, -64.45),
('bn', 'Brunei Darussalam', 'Brunei Darussalam', '文萊', '文莱', 4.3, 114.4),
('bo', 'Bolivia', 'Bolivia', '玻利維亞', '玻利维亚', -17, -65),
('br', 'Brazil', 'Brazil', '巴西', '巴西', -10, -55),
('bs', 'Bahamas', 'Bahamas', '巴哈馬', '巴哈马', 24.15, -76),
('bt', 'Bhutan', 'Bhutan', '不丹', '不丹', 27.3, 90.3),
('bv', 'Bouvet Island', 'Bouvet Island', '布維島', '布维岛', -54.26, 3.24),
('bw', 'Botswana', 'Botswana', '博茨瓦納', '博茨瓦纳', -22, 24),
('by', 'Belarus', 'Belarus', '白俄羅斯', '白俄罗斯', 53, 28),
('bz', 'Belize', 'Belize', '伯利茲', '伯利兹', 17.15, -88.45),
('ca', 'Canada', 'Canada', '加拿大', '加拿大', 60, -95),
('cc', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', '科科斯群島', '科科斯群岛', -12.3, 96.5),
('cf', 'Central African Republic', 'Central African Republic', '中非共和國', '中非共和国', 7, 21),
('cg', 'Congo', 'Congo', '剛果', '刚果', 0, 25),
('ch', 'Switzerland', 'Switzerland', '瑞士', '瑞士', 47, 8),
('ck', 'Cook Islands', 'Cook Islands', '庫克群島', '库克群岛', -21.14, -159.46),
('cl', 'Chile', 'Chile', '智利', '智利', -30, -71),
('cm', 'Cameroon', 'Cameroon', '喀麥隆', '喀麦隆', 6, 12),
('cn', 'China', 'China', '中國', '中国', 35, 105),
('co', 'Colombia', 'Colombia', '哥倫比亞', '哥伦比亚', 4, -72),
('cr', 'Costa Rica', 'Costa Rica', '哥斯達黎加', '哥斯达黎加', 10, -84),
('cs', 'Serbia and Montenegro', 'Serbia and Montenegro', '塞爾維亞和黑山', '塞尔维亚和黑山', 43.57, 21.41),
('cu', 'Cuba', 'Cuba', '古巴', '古巴', 21.3, -80),
('cv', 'Cape Verde', 'Cape Verde', '佛得角', '佛得角', 16, -24),
('cx', 'Christmas Island', 'Christmas Island', '聖誕島', '圣诞岛', -10.3, 105.4),
('cy', 'Cyprus', 'Cyprus', '塞浦路斯', '塞浦路斯', 35, 33),
('cz', 'Czech Republic', 'Czech Republic', '捷克', '捷克', 49.45, 15.3),
('de', 'Germany', 'Germany', '德國', '德国', 51, 9),
('dj', 'Djibouti', 'Djibouti', '吉布提', '吉布提', 11.3, 43),
('dk', 'Denmark', 'Denmark', '丹麥', '丹麦', 56, 10),
('dm', 'Dominica', 'Dominica', '多米尼加', '多米尼加', 15.25, -61.2),
('do', 'Dominican Republic', 'Dominican Republic', '多米尼加共和國', '多米尼加共和国', 19, -70.4),
('dz', 'Algeria', 'Algeria', '阿爾及利亞', '阿尔及利亚', 28, 3),
('ec', 'Ecuador', 'Ecuador', '厄瓜多爾', '厄瓜多尔', -2, -77.3),
('ee', 'Estonia', 'Estonia', '愛沙尼亞', '爱沙尼亚', 59, 26),
('eg', 'Egypt', 'Egypt', '埃及', '埃及', 27, 30),
('eh', 'Western Sahara', 'Western Sahara', '西撒哈拉', '西撒哈拉', 24.3, -13),
('er', 'Eritrea', 'Eritrea', '厄立特里亞', '厄立特里亚', 15, 39),
('es', 'Spain', 'Spain', '西班牙', '西班牙', 40, -4),
('et', 'Ethiopia', 'Ethiopia', '埃塞俄比亞', '埃塞俄比亚', 8, 38),
('fi', 'Finland', 'Finland', '芬蘭', '芬兰', 64, 26),
('fj', 'Fiji', 'Fiji', '斐', '斐', -18, 175),
('fk', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', '福克蘭群島', '福克兰群岛', -51.45, -59),
('fm', 'Micronesia', 'Micronesia', '密克羅尼西亞', '密克罗尼西亚', 6.55, 158.15),
('fo', 'Faroe Islands', 'Faroe Islands', '法羅群島', '法罗群岛', 62, -7),
('fr', 'France', 'France', '法國', '法国', 46, 2),
('ci', 'Cote D’ivoire', 'Ivory Coast', '象牙海岸', '象牙海岸', 7.64, -4.93),
('ga', 'Gabon', 'Gabon', '加蓬', '加蓬', -1, 11.45),
('gd', 'Grenada', 'Grenada', '格林納達', '格林纳达', 12.07, -61.4),
('ge', 'Georgia', 'Georgia', '格魯吉亞', '格鲁吉亚', 42, 43.3),
('gf', 'French Guiana', 'French Guiana', '法屬圭亞那', '法属圭亚那', 4, -53),
('gh', 'Ghana', 'Ghana', '加納', '加纳', 8, -2),
('gi', 'Gibraltar', 'Gibraltar', '直布羅陀', '直布罗陀', 36.8, -5.21),
('gl', 'Greenland', 'Greenland', '格陵蘭', '格陵兰', 72, -40),
('gm', 'Gambia', 'Gambia', '岡比亞', '冈比亚', 13.28, -16.34),
('gn', 'Guinea', 'Guinea', '幾內亞', '几内亚', 11, -10),
('gp', 'Guadeloupe', 'Guadeloupe', '瓜德羅普島', '瓜德罗普岛', 16.15, -61.35),
('gq', 'Equatorial Guinea', 'Equatorial Guinea', '赤道幾內亞', '赤道几内亚', 2, 10),
('gr', 'Greece', 'Greece', '希臘', '希腊', 39, 22),
('gs', 'South Georgia and the South Sandwich Islands', 'S. Georgia and S. Sandwich Isls.', '南喬治亞島和南桑威奇群島', '南乔治亚岛和南桑威奇群岛', -54.3, -37),
('gt', 'Guatemala', 'Guatemala', '危地馬拉', '危地马拉', 15.3, -90.15),
('gu', 'Guam', 'Guam', '關島', '关岛', 13.28, 144.47),
('gw', 'Guinea-Bissau', 'Guinea-Bissau', '幾內亞比紹', '几内亚比绍', 12, -15),
('gy', 'Guyana', 'Guyana', '圭亞那', '圭亚那', 5, -59),
('hk', 'Hong Kong', 'Hong Kong', '香港', '香港', 22.15, 114.1),
('hm', 'Heard Island and Mcdonald Islands', 'Heard and McDonald Islands', '赫德島和麥當勞群島', '赫德岛和麦当劳群岛', -53.06, 72.31),
('hn', 'Honduras', 'Honduras', '洪都拉斯', '洪都拉斯', 15, -86.3),
('hr', 'Croatia (Hrvatska)', 'Croatia (Hrvatska)', '克羅地亞', '克罗地亚', 45.1, 15.3),
('ht', 'Haiti', 'Haiti', '海地', '海地', 19, -72.25),
('hu', 'Hungary', 'Hungary', '匈牙利', '匈牙利', 47, 20),
('id', 'Indonesia', 'Indonesia', '印尼', '印尼', -5, 120),
('ie', 'Ireland', 'Ireland', '愛爾蘭', '爱尔兰', 53, -8),
('il', 'Israel', 'Israel', '以色列', '以色列', 31.3, 34.45),
('in', 'India', 'India', '印度', '印度', 20, 77),
('io', 'British Indian Ocean Territory', 'British Indian Ocean Territory', '英屬印度洋領地', '英属印度洋领地', -6, 71.3),
('iq', 'Iraq', 'Iraq', '伊拉克', '伊拉克', 33, 44),
('ir', 'Iran, Islamic Republic of', 'Iran', '伊朗', '伊朗', 32, 53),
('is', 'Iceland', 'Iceland', '冰島', '冰岛', 65, -18),
('it', 'Italy', 'Italy', '意大利', '意大利', 42.5, 12.5),
('jm', 'Jamaica', 'Jamaica', '牙買加', '牙买加', 18.15, -77.3),
('jo', 'Jordan', 'Jordan', '約旦', '约旦', 31, 36),
('jp', 'Japan', 'Japan', '日本', '日本', 36, 138),
('ke', 'Kenya', 'Kenya', '肯尼亞', '肯尼亚', 1, 38),
('kg', 'Kyrgyzstan', 'Kyrgyzstan', '吉爾吉斯斯坦', '吉尔吉斯斯坦', 41, 75),
('kh', 'Cambodia', 'Cambodia', '柬埔寨', '柬埔寨', 13, 105),
('ki', 'Kiribati', 'Kiribati', '基里巴斯', '基里巴斯', 1.25, 173),
('km', 'Comoros', 'Comoros', '科摩羅', '科摩罗', -12.1, 44.15),
('kn', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', '聖基茨和尼維斯', '圣基茨和尼维斯', 17.2, -62.45),
('kp', 'Korea, Democratic People’s Republic of (North)', 'Korea (North)', '北韓', '北韩', 40, 127),
('kr', 'Korea, Republic of (South)', 'Korea (South)', '韓國', '韩国', 37, 127.3),
('kw', 'Kuwait', 'Kuwait', '科威特', '科威特', 29.3, 45.45),
('ky', 'Cayman Islands', 'Cayman Islands', '開曼群島', '开曼群岛', 19.3, -80.3),
('kz', 'Kazakhstan', 'Kazakhstan', '哈薩克斯坦', '哈萨克斯坦', 48, 68),
('la', 'Lao People’s Democratic Republic', 'Laos', '老撾', '老挝', 18, 105),
('lb', 'Lebanon', 'Lebanon', '黎巴嫩', '黎巴嫩', 33.5, 35.5),
('lc', 'Saint Lucia', 'Saint Lucia', '聖盧西亞', '圣卢西亚', 13.53, -60.68),
('li', 'Liechtenstein', 'Liechtenstein', '列支敦士登', '列支敦士登', 47.16, 9.32),
('lk', 'Sri Lanka', 'Sri Lanka', '斯里蘭卡', '斯里兰卡', 7, 81),
('lr', 'Liberia', 'Liberia', '利比里亞', '利比里亚', 6.3, -9.3),
('ls', 'Lesotho', 'Lesotho', '萊索托', '莱索托', -29.3, 28.3),
('lt', 'Lithuania', 'Lithuania', '立陶宛', '立陶宛', 56, 24),
('lu', 'Luxembourg', 'Luxembourg', '盧森堡', '卢森堡', 49.45, 6.1),
('lv', 'Latvia', 'Latvia', '拉脫維亞', '拉脱维亚', 57, 25),
('ly', 'Libyan Arab Jamahiriya', 'Libya', '利比亞', '利比亚', 25, 17),
('ma', 'Morocco', 'Morocco', '摩洛哥', '摩洛哥', 32, -5),
('mc', 'Monaco', 'Monaco', '摩納哥', '摩纳哥', 43.44, 7.24),
('md', 'Moldova', 'Moldova', '摩爾多瓦', '摩尔多瓦', 47, 29),
('mg', 'Madagascar', 'Madagascar', '馬達加斯加', '马达加斯加', -20, 47),
('mh', 'Marshall Islands', 'Marshall Islands', '馬紹爾群島', '马绍尔群岛', 9, 168),
('mk', 'Macedonia, the Former Yugoslav Republic of', 'Macedonia', '馬其頓', '马其顿', 41.5, 22),
('ml', 'Mali', 'Mali', '馬里', '马里', 17, -4),
('mm', 'Myanmar', 'Burma (Myanmar)', '緬甸', '缅甸', 22, 98),
('mn', 'Mongolia', 'Mongolia', '蒙古', '蒙古', 46, 105),
('mo', 'Macau', 'Macau', '澳門', '澳门', 22.1, 113.33),
('mp', 'Northern Mariana Islands', 'Northern Mariana Islands', '北馬里亞納群島', '北马里亚纳群岛', 15.12, 145.45),
('mq', 'Martinique', 'Martinique', '馬提尼克島', '马提尼克岛', 14.4, -61),
('mr', 'Mauritania', 'Mauritania', '毛里塔尼亞', '毛里塔尼亚', 20, -12),
('ms', 'Montserrat', 'Montserrat', '蒙特塞拉特', '蒙特塞拉特', 16.45, -62.12),
('mt', 'Malta', 'Malta', '馬耳他', '马耳他', 35.5, 14.35),
('mu', 'Mauritius', 'Mauritius', '毛里求斯', '毛里求斯', -20.17, 57.33),
('mv', 'Maldives', 'Maldives', '馬爾代夫', '马尔代夫', 3.15, 73),
('mw', 'Malawi', 'Malawi', '馬拉維', '马拉维', -13.3, 34),
('mx', 'Mexico', 'Mexico', '墨西哥', '墨西哥', 23, -102),
('my', 'Malaysia', 'Malaysia', '馬來西亞', '马来西亚', 2.3, 112.3),
('mz', 'Mozambique', 'Mozambique', '莫桑比克', '莫桑比克', -18.15, 35),
('na', 'Namibia', 'Namibia', '納米比亞', '纳米比亚', -22, 17),
('nc', 'New Caledonia', 'New Caledonia', '新喀裡多尼亞', '新喀里多尼亚', -21.3, 165.3),
('ne', 'Niger', 'Niger', '尼日爾', '尼日尔', 16, 8),
('nf', 'Norfolk Island', 'Norfolk Island', '諾福克島', '诺福克岛', -29.02, 167.57),
('ng', 'Nigeria', 'Nigeria', '尼日利亞', '尼日利亚', 10, 8),
('ni', 'Nicaragua', 'Nicaragua', '尼加拉瓜', '尼加拉瓜', 13, -85),
('nl', 'Netherlands', 'Netherlands', '荷蘭', '荷兰', 52.3, 5.45),
('no', 'Norway', 'Norway', '挪威', '挪威', 62, 10),
('np', 'Nepal', 'Nepal', '尼泊爾', '尼泊尔', 28, 84),
('nr', 'Nauru', 'Nauru', '瑙魯', '瑙鲁', -0.32, 166.55),
('nt', 'Neutral Zone', 'Neutral Zone', '中立區', '中立区', 0, 0),
('nu', 'Niue', 'Niue', '紐埃', '纽埃', -19.02, -169.52),
('nz', 'New Zealand', 'New Zealand (Aotearoa)', '新西蘭', '新西兰', -41, 174),
('om', 'Oman', 'Oman', '阿曼', '阿曼', 21, 57),
('pa', 'Panama', 'Panama', '巴拿馬', '巴拿马', 9, -80),
('pe', 'Peru', 'Peru', '秘魯', '秘鲁', -10, -76),
('pf', 'French Polynesia', 'French Polynesia', '法屬波利尼西亞', '法属波利尼西亚', -15, -140),
('pg', 'Papua New Guinea', 'Papua New Guinea', '巴布亞新幾內亞', '巴布亚新几内亚', -6, 147),
('ph', 'Philippines', 'Philippines', '菲律賓', '菲律宾', 13, 122),
('pk', 'Pakistan', 'Pakistan', '巴基斯坦', '巴基斯坦', 30, 70),
('pl', 'Poland', 'Poland', '波蘭', '波兰', 52, 20),
('pm', 'Saint Pierre and Miquelon', 'St. Pierre and Miquelon', '聖皮埃爾和密克隆', '圣皮埃尔和密克隆', 46.5, -56.2),
('pn', 'Pitcairn', 'Pitcairn', '皮特凱恩', '皮特凯恩', -25.04, -130.06),
('pr', 'Puerto Rico', 'Puerto Rico', '波多黎各', '波多黎各', 18.15, -66.3),
('pt', 'Portugal', 'Portugal', '葡萄牙', '葡萄牙', 39.3, -8),
('pw', 'Palau', 'Palau', '帕勞', '帕劳', 7.3, 134.3),
('py', 'Paraguay', 'Paraguay', '巴拉圭', '巴拉圭', -23, -58),
('qa', 'Qatar', 'Qatar', '卡塔爾', '卡塔尔', 25.3, 51.15),
('re', 'Reunion', 'Reunion', '團圓', '团圆', -21.06, 55.36),
('ro', 'Romania', 'Romania', '羅馬尼亞', '罗马尼亚', 46, 25),
('ru', 'Russian Federation', 'Russia', '俄國', '俄国', 60, 100),
('rw', 'Rwanda', 'Rwanda', '盧旺達', '卢旺达', -2, 30),
('sa', 'Saudi Arabia', 'Saudi Arabia', '沙特阿拉伯', '沙特阿拉伯', 25, 45),
('sb', 'Solomon Islands', 'Solomon Islands', '索羅門群島', '索罗门群岛', -8, 159),
('sc', 'Seychelles', 'Seychelles', '塞舌爾', '塞舌尔', -4.35, 55.4),
('sd', 'Sudan', 'Sudan', '蘇丹', '苏丹', 15, 30),
('se', 'Sweden', 'Sweden', '瑞典', '瑞典', 62, 15),
('sg', 'Singapore', 'Singapore', '新加坡', '新加坡', 1.22, 103.48),
('sh', 'Saint Helena', 'St. Helena', '聖赫勒拿島', '圣赫勒拿岛', -15.56, -5.42),
('si', 'Slovenia', 'Slovenia', '斯洛文尼亞', '斯洛文尼亚', 46.07, 14.49),
('sj', 'Svalbard and Jan Mayen Islands', 'Svalbard and Jan Mayen Islands', '斯瓦爾巴群島和揚馬延島', '斯瓦尔巴群岛和扬马延岛', 78, 20),
('sk', 'Slovakia', 'Slovak Republic', '斯洛伐克', '斯洛伐克', 48.4, 19.3),
('sl', 'Sierra Leone', 'Sierra Leone', '塞拉利昂', '塞拉利昂', 8.3, -11.3),
('sm', 'San Marino', 'San Marino', '聖馬力諾', '圣马力诺', 43.46, 12.25),
('sn', 'Senegal', 'Senegal', '塞內加爾', '塞内加尔', 14, -14),
('so', 'Somalia', 'Somalia', '索馬里', '索马里', 10, 49),
('sr', 'Suriname', 'Suriname', '蘇里南', '苏里南', 4, -56),
('st', 'Sao Tome and Principe', 'Sao Tome and Principe', '聖多美和普林西比', '圣多美和普林西比', 1, 7),
('sv', 'El Salvador', 'El Salvador', '薩爾瓦多', '萨尔瓦多', 13.5, -88.55),
('sy', 'Syrian Arab Republic', 'Syrian Arab Republic', '敘利亞', '叙利亚', 35, 38),
('sz', 'Swaziland', 'Swaziland', '斯威士蘭', '斯威士兰', -26.3, 31.3),
('tc', 'Turks and Caicos Islands', 'Turks and Caicos Islands', '特克斯和凱科斯群島', '特克斯和凯科斯群岛', 21.45, -71.35),
('td', 'Chad', 'Chad', '乍得', '乍得', 15, 19),
('tf', 'French Southern Territories', 'French Southern Territories', '法國南部領土', '法国南部领土', -43, 67),
('tg', 'Togo', 'Togo', '多哥', '多哥', 8, 1.1),
('th', 'Thailand', 'Thailand', '泰國', '泰国', 15, 100),
('tj', 'Tajikistan', 'Tajikistan', '塔吉克斯坦', '塔吉克斯坦', 39, 71),
('tk', 'Tokelau', 'Tokelau', '托克勞', '托克劳', -9, -172),
('tm', 'Turkmenistan', 'Turkmenistan', '土庫曼斯坦', '土库曼斯坦', 40, 60),
('tn', 'Tunisia', 'Tunisia', '突尼斯', '突尼斯', 34, 9),
('to', 'Tonga', 'Tonga', '湯加', '汤加', -20, -175),
('tl', 'Timor-Leste', 'East Timor', '東帝汶', '东帝汶', -8.5, 125.55),
('tr', 'Turkey', 'Turkey', '土耳其', '土耳其', 39, 35),
('tt', 'Trinidad and Tobago', 'Trinidad and Tobago', '特里尼達和多巴哥', '特里尼达和多巴哥', 11, -61),
('tv', 'Tuvalu', 'Tuvalu', '圖瓦盧', '图瓦卢', -8, 178),
('tw', 'Taiwan', 'Taiwan', '台灣', '台湾', 23.3, 121),
('tz', 'Tanzania, United Republic of', 'Tanzania', '坦桑尼亞', '坦桑尼亚', -6, 35),
('ua', 'Ukraine', 'Ukraine', '烏克蘭', '乌克兰', 49, 32),
('ug', 'Uganda', 'Uganda', '烏干達', '乌干达', 1, 32),
('uk', 'United Kingdom', 'United Kingdom', '英國', '英国', 54, -2),
('us', 'United States', 'United States', '美國', '美国', 38, -97),
('uy', 'Uruguay', 'Uruguay', '烏拉圭', '乌拉圭', -33, -56),
('uz', 'Uzbekistan', 'Uzbekistan', '烏茲別克斯坦', '乌兹别克斯坦', 41, 64),
('va', 'Vatican City State', 'Vatican City State (Holy See)', '教廷', '教廷', 41.54, 12.27),
('vc', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', '聖文森特和格林納丁斯', '圣文森特和格林纳丁斯', 13.15, -61.12),
('ve', 'Venezuela', 'Venezuela', '委內瑞拉', '委内瑞拉', 8, -66),
('vg', 'Virgin Islands, British', 'Virgin Islands (British)', '英屬維爾京群島', '英属维尔京群岛', 18.2, -64.5),
('vi', 'Virgin Islands, U.S.', 'Virgin Islands (U.S.)', '美國維爾京群島', '美国维尔京群岛', 18.2, -64.5),
('vn', 'Viet Nam', 'Viet Nam', '越南', '越南', 16, 106),
('vu', 'Vanuatu', 'Vanuatu', '瓦努阿圖', '瓦努阿图', -16, 167),
('wf', 'Wallis and Futuna Islands', 'Wallis and Futuna Islands', '瓦利斯群島和富圖納群島', '瓦利斯群岛和富图纳群岛', -13.18, -176.12),
('ws', 'Samoa', 'Samoa', '薩摩亞', '萨摩亚', -13.35, -172.2),
('ye', 'Yemen', 'Yemen', '也門', '也门', 15, 48),
('yt', 'Mayotte', 'Mayotte', '馬約特島', '马约特岛', -12.5, 45.1),
('yu', 'Yugoslavia', 'Yugoslavia', '南斯拉夫', '南斯拉夫', 44, 21),
('za', 'South Africa', 'South Africa', '南非', '南非', -29, 24),
('zm', 'Zambia', 'Zambia', '贊比亞', '赞比亚', -15, 30),
('cd', 'Congo, Democratic Republic of the', 'Democratic Republic of Congo', '剛果民主共和國', '刚果民主共和国', -4.04, 30.75),
('zw', 'Zimbabwe', 'Zimbabwe', '津巴布韋', '津巴布韦', -20, 30),
('ap', '', 'Asia-Pacific', '亞太', '亚太', -2.81, 128.5),
('rs', 'Serbia', 'Republic of Serbia', '塞爾維亞', '塞尔维亚', 44.02, 21.01),
('ax', 'Aland Islands', 'Åland Islands', '奧蘭群島', '奥兰群岛', 60.21, 20.16),
('eu', '', 'Europe', '歐洲', '欧洲', 50, 15),
('01', '', 'Private', '私有', '私有', 0, 0),
('ps', 'Palestinian Territory, Occupied', 'Palestinian Territory, Occupied', '巴勒斯坦', '巴勒斯坦', 31.89, 34.9),
('me', 'Montenegro', 'Montenegro', '黑山', '黑山', 42.74, 19.31);
